# -*- coding: utf-8 -*-
"""Video 14 — 昭和の職場 (5 muc). Cong thuc duy nhat v2.

⛔ KHONG chep hang so. STYLE / MOTION / AVOID / FRAMING / EXTRAS deu lay tu videogen_lib.

HAI THU KHAC MOI VIDEO TRUOC:
 1. ⭐ **90% POV** (user chot 2026-09-14). Video 13 chi 10%. Day la dao han ngon ngu hinh.
 2. ⭐ **MOT doi mat duy nhat: A_OJI** (ong bac, 19 tuoi nam 1969 — xuong song cua kich ban).
    Day KHONG phai lua chon tham my, no la cach giai bai toan "nhan vat dong nhat":
    90% khung nhin qua mot nguoi => ca video chi co MOT than nguoi phai giu (tay ao xan,
    cang tay, nguc ao) thay vi 5-6 dan dien phai khop nhau qua 134 clip.

🔴 BA RUI RO CUA 90% POV — biet truoc, khong phat hien lai:
 a. POV la loai shot t2v hong nhieu nhat (`hands only` an 14/21 clip o video 10).
    => MOI shot POV deu phai co THAN trong khung: dung pov/pov_sit/pov_stand (co than),
       chi dung pov_hand khi that su chi can hai ban tay.
 b. Thieu khoa `<cast>_pov*` trong C thi build() am tham roi ve mo ta NHIN TU NGOAI
    (bug bat duoc o video 13, `videogen_lib.build`). A_OJI da co du 5 bien the.
 c. 90% mot goc may lien tuc de gay MET. Da tron 5 kieu POV + 13 shot ngoi-thu-ba lam nhip tho.
"""
import sys
sys.path.insert(0, r"E:\Claude\Projects\youtube-jp-showa\tools")
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
from videogen_lib import build, gate, write_outputs, autochain, linkage, act_report

P = {
 "eki_asa":  "the platform of a Showa commuter station on a Saturday morning, a long concrete platform under a steel canopy, a wooden bench, painted lane marks on the ground, the rails and low town roofs beyond",
 "office":   "a Showa company office, steel desks pushed together in facing rows, a black dial telephone on each island, an abacus and a mechanical calculator, glass ashtrays, steel filing cabinets along the wall, a wall clock and a blackboard of duty rosters, a long run of steel-framed windows down one side and a tall window at the far end, a ceiling fan turning overhead, and a plain corridor running out from the door of the room with a tall window at the end of it",
 "kyutou":   "the small tea room of a Showa office, a gas ring with a kettle on it, a shelf of teacups in a fixed row, a wooden tray and saucers, a steel sink, steam on the small window",
 "ginkou":   "a street outside a Showa branch bank, a tiled frontage with a heavy glass door, a bicycle rack, low shopfronts along the pavement",
 "shotengai":"a Showa shopping street in the early evening, awnings out over the pavement, a fishmonger and a shoe shop with goods in open boxes, bare bulbs strung over the street",
 # pho xa buoi TRUA — tach rieng khoi `shotengai` (buoi chieu). B20 thuoc muc 1
 # (thu Bay lam nua ngay, tan luc TRUA) nen buoi trua CHINH LA noi dung cua canh;
 # 6/7 canh shotengai con lai la chieu/toi va dung, chi B20 lech.
 "shotengai_hiru":"a Showa shopping street at midday, awnings out over the pavement, a vegetable shop and a fishmonger with goods in open boxes, the shutters of the closed shops still up, flat bright daylight down the length of the street",
 "office_rouka":"the corridor of a Showa office block, a plain painted wall with a line of doors down one side, a worn linoleum floor, and a tall steel-framed window at the far end looking straight out over the low roofs of the town",
 "genkan":   "the entrance hall of a Showa house in the evening, a concrete step with shoes set out on it, a sliding frosted glass door, a narrow wooden corridor going into the house",
 "densha":    "the inside of a crowded Showa commuter train in the morning, fabric bench seats full, a solid row of hanging straps, standing passengers shoulder to shoulder in the aisle, town roofs going past the windows",
 "densha_hiru":"the inside of a Showa commuter train in the middle of the day, fabric bench seats almost empty, hanging straps still, flat daylight through the windows",
 "izakaya":  "a small Showa eating house at night, a long low table with beer bottles and small dishes on it, a short split curtain over the doorway, paper lanterns and a strip of handwritten menu cards on the wall",
 "soubetsu": "a corner of a Showa office cleared for a send-off, desks pushed back, a bunch of flowers wrapped in paper on a desk, a sheet of coloured paper covered in handwriting face down, teacups set out",
 "ima_office":"a present-day Japanese office, low partitions, laptops and flat screens, a paper cup of coffee, plain grey carpet, daylight through a wide window",
}

C = {
 # ⭐ MOT nhan vat POV duy nhat cho ca video — nguon cua "nhan vat dong nhat"
 "oji":          "a young man in a plain white short-sleeved dress shirt and dark trousers",
 "oji_pov":      "their own forearms and the plain white shirt on their own chest, the sleeves rolled twice",
 # ⛔ KHONG ghi "under a steel desk": pov_sit con dung o hanh lang nha, quan an, tau trua
 "oji_pov_sit":  "their own forearms and the plain white shirt on their own chest, the sleeves rolled twice, and their own knees and lap across the bottom of the picture",
 "oji_pov_stand":"their own forearms and the plain white shirt on their own chest, the sleeves rolled twice",
 "oji_pov_hand": "their own forearms in rolled white shirt sleeves and the backs of their own hands",
 "oji_pov_walk": "only their own hand or hands where the work needs them, rolled white shirt cuffs at the edge",
 # nhung nguoi ong ay NHIN THAY
 "kachou":  "a man in his fifties in a plain white dress shirt and a dark tie, sleeves buttoned at the wrist",
 "senpai":  "a man in his early fifties in a plain grey work jacket over a white shirt",
 "jimu":    "a young woman in a plain white blouse and a dark skirt with a plain dark apron over it",
 "unten":   "a man in a plain grey work jacket",
 "ima":     "a woman in plain modern office clothes, a plain pale blouse and dark trousers",
 "ima_pov": "their own forearms and a plain pale modern sleeve at the edge",
 "ima_pov_walk":"only their own hand or hands where the work needs them, plain modern sleeves at the edge",
 "ima_pov_hand":"their own forearms and the backs of their own hands, plain modern sleeves at the edge",
}

CROWD = {
 "densha": "full",
 "office": "full", "eki_asa": "full", "ginkou": "few", "shotengai": "full",
 "shotengai_hiru": "full", "office_rouka": "few",
 "densha_hiru": ("solo", "tau giua trua — vang la NOI DUNG cua canh"),
 "kyutou":  ("solo", "phong pha tra — mot nguoi mot luot"),
 "genkan":  "few", "soubetsu": "few", "izakaya": "full",
 "ima_office": ("solo", "van phong nay — mot nguoi mot man hinh, do la LUAN DIEM"),
}

S = []

# =====================================================================================
# HOOK 00-07 — E7: hanh vi -> he qua -> chung nhan -> 3 cu soc -> dan nhan
#   Hinh mo bai: HAI NGUOI OM BOC TIEN LUONG CA CONG TY TU NGAN HANG VE
# =====================================================================================
S += [
('H0','HOOK',"A_OJI: the pavement outside the branch bank fills the view with two men in grey work jackets coming out of the heavy glass door towards them, one of them holding a large cloth bundle against his chest, then the bundle passes close by the view, then the view carries after them along the pavement left to right, while the awnings move in the wind, as shoppers step aside to let them through",'ginkou','pov_look','Q',None,None),
('H1','HOOK',"A_SENPAI, seen from behind the whole time, carries a large cloth bundle against his chest the whole length of the office aisle between the facing desks, then sets it down on the end desk, then unties the knot and folds the cloth back, while the ceiling fan turns overhead and its shadow moves across the desks, as the whole floor goes quiet and heads come up from the desks",'office','wide','Q','A','A_SENPAI standing over the opened cloth bundle on the desk'),
('H2','HOOK',"A_OJI: the steel desk fills the bottom of the view with banded bundles of banknotes standing on the opened cloth, then two hands come into the frame and lift one band clear, then the thumb riffles the notes once and sets the band down beside the others",'office','pov_hand','Q','A',None),
('H3','HOOK',"A_OJI: a row of brown paper envelopes lies across the desk in the bottom of the view, each with a name written on it, then their own hand slides a folded set of notes into the nearest envelope, then presses the flap flat with the thumb and moves it onto the finished pile",'office','pov_hand','Q',None,None),
('H4','HOOK',"A_OJI: the office platform of the Saturday station fills the view with the crowd standing at the painted marks, then the view turns to the left along the whole length of the platform, then settles on the rails where the train is coming in, while the wind moves along the platform, as the crowd shifts forward together",'eki_asa','pov_look','Q',None,None),
('H5','HOOK',"A_JIMU, seen from behind the whole time, carries a tray of teacups the whole width of the office from the tea room door to the far desks, then stops at the first island and sets one cup down, then straightens and carries the tray on out of frame, while steam rises from the cups, as two men at the desks keep talking without looking up",'office','wide','Q',None,None),
('H6','HOOK',"A_OJI: the desks of the far end of the office fill the view with a man standing over a seated one, then a sheet of paper slides off the far desk and drops to the floor, then every head in the view stays down and nobody looks up, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_look','Q',None,None),
('H7','HOOK',"A_OJI: the cleared corner of the office fills the view with a wrapped bunch of flowers lying on a desk, then their own hand comes into the frame and turns the flowers a little so the paper faces the room, then withdraws and leaves them lying there, while the light from the window moves across the desk",'soubetsu','pov_sit','Q',None,None),
('H8','HOOK',"A_OJI: the office fills the view with the two rows of desks at work, then the view turns up to the wall clock standing at half past eleven on a Saturday, then comes back down to their own ledger, while the shadow of the ceiling fan moves across the desks, as the clerks on both sides work on",'office','pov_look','Q',None,None),
('H9','HOOK',"A_OJI: the desk fills the bottom of the view with a brown envelope and a teacup standing side by side on it, then their own hand moves the cup clear of the envelope, then rests flat between them, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
]

# =====================================================================================
# INTRO 08-11
# =====================================================================================
S += [
('A0','INTRO',"A_OJI: the office aisle runs away ahead of the view between two rows of facing steel desks, then the view carries the whole length of the aisle past the desks, then stops at the window at the far end, the whole move running left to right across the frame, while the ceiling fan turns overhead and its shadow moves across the desks, as clerks work at every desk on both sides",'office','pov_look','Q',None,None),
('A1','INTRO',"A_OJI: their own two hands come into the frame over an empty steel desk, then set down a cloth cap and a folded newspaper on the corner of it, then pull the chair out and settle in front of the desk, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov','Q',None,None),
('A2','INTRO',"A_IMA: the low partitioned desk fills the view in the bright modern office, then their own hand opens a laptop on it, then sets a paper cup down beside it, while the curtain at the wide window stirs",'ima_office','pov','Q',None,None),
('A3','INTRO',"A_OJI: the wall of steel filing cabinets fills the view with the wall clock above them, then their own hand takes hold of one drawer handle and draws the drawer out until it stops, then lifts a bundle of folders halfway up out of it and lets them settle back, while the shadow of the ceiling fan moves across the cabinets",'office','pov_hand','Q',None,None),
('A4','INTRO',"A_OJI: the office window fills the view with the town roofs beyond it, then the view comes back in along the desks to their own place, then settles on the empty desktop, while the curtain at the window stirs, as clerks settle in at the desks on both sides",'office','pov_look','Q',None,None),
('A5','INTRO',"A_OJI: the office doorway opens out ahead of the view onto the two rows of desks, then the view carries in along the aisle left to right across the frame, then stops as the men at the nearest desks look up from their work and one of them lifts a hand in greeting, while the shadow of the ceiling fan moves across the desks, as heads come up along both rows",'office','pov_look','Q','E',"the men at the nearest desks looking up with a hand lifted in greeting",'warm'),
('A6','INTRO',"A_SENPAI turns from the next desk and bows his head a little in greeting, then says something short over the ledgers, then goes back to the open page in front of him, while the shadow of the ceiling fan moves across the desks, as the clerks on both sides work on",'office','ots','Q','E',None,'warm'),
]

# =====================================================================================
# MUC 1 — 土曜日も会社に行くもの (12-33)
# =====================================================================================
S += [
('B0','M1',"A_OJI: the mouth of the platform opens out ahead of the view past the ticket barrier, then the view carries out from under the barrier into the open canopy left to right across the frame, then stops short of the painted marks where the Saturday crowd is already standing, while the wind moves along the platform, as more people come out of the barrier behind them",'eki_asa','pov_look','Q',None,None),
('B1','M1',"A_OJI: the bench on the platform fills the bottom of the view with a canvas bag and a rod case leaning against it, then their own hand comes into the frame and stands the rod case upright, then lets go and withdraws, while the wind moves along the platform",'eki_asa','pov_hand','Q',None,None),
('B2','M1',"A_OJI: the inside of the crowded train fills the view with the row of hanging straps above, then their own hand reaches up and takes hold of the nearest strap, then the whole view sways once with the carriage and settles, while the whole carriage sways together on the rails",'densha','pov_stand','Q',None,None),
('B3','M1',"A_OJI: the office aisle fills the view with clerks already at every desk, then the view turns to the right to their own desk, then settles on the desktop where a ledger lies open, while the ceiling fan turns overhead and its shadow moves across the desks, as the room fills with the sound of work",'office','pov_look','Q',None,None),
('B4','M1',"A_OJI: the open ledger fills the bottom of the view on the steel desk, then their own left hand flicks the beads of an abacus twice, then the right hand writes a figure into the ruled column and lifts the pen away, while the shadow of the ceiling fan moves across the page",'office','pov_hand','Q',None,None),
('B5','M1',"A_OJI: the wall clock at the end of the office fills the view with the hands standing just before twelve, then the view drops back down to the desk, then the hands come into frame and begin stacking the papers together, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_look','Q',None,None),
('B6','M1',"A_OJI: the head of the office fills the view as the man at the front desk stands up and looks along the two rows, then the view turns from him along the desks on both sides, then comes back as he lifts his jacket off the chair, while the shadow of the ceiling fan moves across the desks, as the clerks all round begin closing their ledgers",'office','pov_look','Q',None,None),
('B7','M1',"A_OJI: the office fills the view as every desk begins to move at once, then their own hands pull the desk drawer open and drop the pen into it, then push it shut and rest flat on the empty desktop, while the ceiling fan turns overhead and its shadow moves across the desks, as clerks all round stand and reach for their jackets",'office','pov_sit','Q',None,None),
('B8','M1',"A_OJI: the black telephone on the desk island fills the view and it is ringing, then the view holds on it while it rings, then turns away to the aisle where everyone is leaving, while the ceiling fan turns overhead and its shadow moves across the desks, as nobody in the view goes near it",'office','pov_look','Q',None,None),
('B9','M1',"A_OJI: the desktop fills the bottom of the view, then their own hand wipes a cloth once across it from the near edge to the far edge, then folds the cloth and takes it away out of the bottom of the frame",'office','pov_hand','Q',None,None),
('B10','M1',"A_OJI: the ruled page of a printed law book fills the view on the desk, then their own finger moves along one line to the figure written there, then stops under it and stays, while the light from the window moves across the page",'office','pov_hand','Q',None,None),
('B11','M1',"A_OJI: the tiled frontage of the branch bank fills the view from the pavement, then the view turns to the notice board beside the glass door, then holds on the blank board, while the awnings move in the wind, as customers go in and out of the door",'ginkou','pov_look','Q',None,None),
('B12','M1',"A_OJI: the platform fills the view on a later Saturday and it is nearly empty, then the view turns the whole length of it and finds only two people waiting, then settles on the empty painted marks, while the wind moves along the platform",'eki_asa','pov_look','Q',None,None),
('B13','M1',"A_OJI: the shopping street fills the view under the strung bulbs, then the view turns to a small eating house with its curtain out, then carries towards the doorway until the counter shows inside, the whole move running left to right across the frame, while the awnings move in the wind, as people pass along the pavement both ways",'shotengai','pov_look','Q',None,None),
('B14','M1',"A_OJI: the counter of the eating house fills the bottom of the view with a bowl set down on it, then their own hands come into the frame and take up the bowl and the chopsticks, then lift the bowl towards the view, while steam rises from the bowl",'shotengai','pov_sit','Q',None,None),
('B15','M1',"A_OJI: the station stairs run up ahead of the view towards the platform, then the view carries up them into the light at the top, then comes out under the canopy, the whole move running left to right across the frame, while the wind moves along the platform, as commuters come up the stairs on both sides",'eki_asa','pov_look','Q',None,None),
('B16','M1',"A_OJI: the platform noticeboard fills the view with the timetable pasted on it, then their own finger moves across to the Saturday column, then stops on the last figure in it, while the wind moves the loose corner of the paper",'eki_asa','pov_hand','Q',None,None),
('B17','M1',"A_OJI: the carriage window fills the view with the town going past outside, then the view holds on the low roofs and the factory sheds, then turns back into the crowded carriage, while the whole carriage sways together on the rails",'densha','pov_look','Q',None,None),
('B18','M1',"A_OJI: their own desk fills the bottom of the view with a stack of invoices on it, then their own hand takes the top one off and lays it to the left, then takes the next and lays it on the first, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
('B19','M1',"A_OJI: the office fills the view at noon with the desks emptying, then the view turns to the doorway where the clerks are going out, then settles on the last few still at their desks, while the shadow of the ceiling fan moves across the desks, as more clerks leave through the doorway",'office','pov_look','Q',None,None),
('B20','M1',"A_OJI: the shopping street fills the view at midday with the shutters of the closed shops still up, then the view turns to the vegetable boxes where a queue of baskets has formed, then settles further along on the fishmonger where the ice is being raked flat, while the awnings move in the wind, as people pass along the pavement both ways",'shotengai_hiru','pov_look','Q',None,None),
('B21','M1',"A_OJI: the facing desk fills the view with three colleagues leaning back from their work at noon, then one of them says something and spreads both hands wide, then all three break into laughter together, while the shadow of the ceiling fan moves across the desks, as the rest of the room begins to stand up",'office','pov_sit','Q','F',"the three colleagues at the facing desk laughing together",'warm'),
('B22','M1',"A_SENPAI leans in over the facing desk and says something to the man beside him, then the two of them laugh, then he straightens up and lifts his jacket off the back of the chair, while the shadow of the ceiling fan moves across the desks, as the room empties around them",'office','ots','Q','F',None,'warm'),
('B23','M1',"A_OJI: the long low table fills the view with four colleagues sitting along the far side of it, then the man opposite fills a small glass and pushes it across the table towards them, then the whole table lifts their glasses together, while the lanterns sway a little over the doorway, as more people come in under the split curtain",'izakaya','pov_sit','Q','G',"the whole table with their glasses lifted",'warm'),
('B24','M1',"A_SENPAI raises a small glass at the middle of the long table, then the two men across from him laugh at something he says, then they all set their glasses down together, while the lanterns sway a little over the doorway, as the room fills around them",'izakaya','ots','Q','G',None,'warm'),
]

# =====================================================================================
# MUC 2 — 給料は封筒の現金 (34-53)
# =====================================================================================
S += [
('C0','M2',"A_OJI: the office door stands open ahead of the view on the last Saturday of the month, then the view carries through it and down the aisle towards their own desk left to right across the frame, then stops as a man at the head of the room gets to his feet holding a list, while the shadow of the ceiling fan moves across the desks, as heads come up at every desk in the view",'office','pov_look','Q',None,None),
('C1','M2',"A_KACHOU reads a name off the list at the head of the office and holds out a brown envelope, then a hand comes in and takes it, then he moves his thumb down the list to the next line, while the ceiling fan turns overhead and its shadow moves across the desks, as a short queue forms along the aisle behind",'office','ots','Q','B','A_KACHOU holding the next envelope out over the list'),
('C2','M2',"A_OJI: the head of the room fills the view with the man holding out a brown envelope towards them, then their own hand comes into the frame and takes it, then turns it over so the written name faces up, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_stand','Q','B',None),
('C3','M2',"A_OJI: the brown envelope lies across both their own hands in the bottom of the view, then the thumb and finger press along the edge of it once to feel the thickness, then the hands turn it over and hold it still, while the shadow of the ceiling fan moves across their hands",'office','pov_hand','Q',None,None),
('C4','M2',"A_OJI: the desk fills the bottom of the view with a receipt book open on it, then their own hand presses a small seal onto the pad and then onto the line, then lifts it away leaving the mark, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
('C5','M2',"A_OJI: the desk fills the bottom of the view with the brown envelope lying on an opened square of cloth, then their own hands fold two corners of the cloth in over the envelope, then knot the other two corners across the top of it, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
('C6','M2',"A_OJI: the shopping street in the early evening fills the view with the shops still open and lit, then the view carries the whole length of the pavement past the fishmonger, then slows in front of a shoe shop with boxes out, the whole move running left to right across the frame, while the awnings move in the wind, as the street fills with people coming home",'shotengai','pov_look','Q',None,None),
('C7','M2',"A_OJI: the open boxes outside the shoe shop fill the bottom of the view, then their own hand lifts out one very small shoe and turns it over, then sets it back into the box and withdraws, while the awnings move in the wind",'shotengai','pov_hand','Q',None,None),
('C8','M2',"A_OJI: the frosted glass door of the house entrance fills the view from outside, then the view moves towards it until the step and the shoes on it come in, then the door slides back, while the shadow of the door frame moves across the step",'genkan','pov_look','Q',None,None),
('C9','M2',"A_OJI: the entrance hall fills the view with a woman standing on the step above, then their own hand comes into the frame and holds the brown envelope out towards her, then the envelope leaves their hand and the hand lowers, while the shadow of the door frame moves across the step",'genkan','pov_stand','Q',None,None),
('C10','M2',"A_OJI: the low table in the corridor fills the view with the opened envelope on it and a woman in a plain house apron kneeling at the far side of it, then she counts the notes out onto the wood one by one, then she squares the counted pile and slides it back across the table towards them, while the shadow of the lamp cord sways a little over the wood",'genkan','pov_sit','Q',None,None),
('C11','M2',"A_OJI: the ruled page of a printed law book fills the view on the desk, then their own two fingers move down the printed article to the line about payment in currency, then stop under it and stay, while the light from the window moves across the page",'office','pov_hand','Q',None,None),
('C12','M2',"A_OJI: the desk fills the view with a bank passbook lying closed on it, then their own hand opens the cover and turns to the first ruled page, then holds it flat and stays, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_hand','Q',None,None),
('C13','M2',"A_IMA: the modern desk fills the bottom of the view with a phone lying face up on it, then their own hand turns the phone over and the screen lights, then the hand withdraws and leaves it lying there",'ima_office','pov_hand','Q',None,None),
('C14','M2',"A_OJI: the office at the end of the month fills the view with the emptied cloth folded on the end desk, then their own hand comes into the frame and folds the cloth once more, then lays it flat on the corner of the desk and rests a hand on it, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_hand','Q',None,None),
('C15','M2',"A_OJI: the office aisle runs away ahead of the view towards the end desk where the cloth lies open, then the view carries the length of the aisle towards it, then stops at the desk, the whole move running left to right across the frame, while the shadow of the ceiling fan moves across the desks, as clerks look up from the desks on both sides",'office','pov_look','Q',None,None),
('C16','M2',"A_OJI: the end desk fills the bottom of the view with the banded notes standing on the opened cloth, then their own hand squares two bands together, then sets them back down in the row, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
('C17','M2',"A_OJI: the queue along the aisle fills the view with clerks waiting with their hands at their sides, then the view turns down the line to the head of the room, then comes back to the man in front of them, while the shadow of the ceiling fan moves across the desks, as the line shuffles forward one place",'office','pov_look','Q',None,None),
('C18','M2',"A_OJI: the desk fills the bottom of the view with the envelope lying on it, then their own thumb turns the flap up and the edges of the notes show inside, then presses the flap back down flat, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
('C19','M2',"A_OJI: the shopping street fills the view with a fish stall out under the awning, then their own hand points to one fish on the ice, then lowers again out of the frame, while the awnings move in the wind, as shoppers crowd in along the stall",'shotengai','pov_stand','Q',None,None),
('C20','M2',"A_OJI: the corridor of the house fills the view with the low table and the counted notes on it, then the view turns from the table to the doorway of the room beyond, then holds on the light in the doorway, while the shadow of the window bars moves along the floor",'genkan','pov_look','Q',None,None),
('C21','M2',"A_OJI: the queue along the aisle fills the view with the men ahead of them holding brown envelopes, then the two at the front turn to each other and weigh theirs in their hands, then both of them laugh and move along, while the shadow of the ceiling fan moves across the desks, as the line shuffles forward one place",'office','pov_stand','Q','H',"the two men at the front of the queue laughing over their envelopes",'warm'),
('C22','M2',"A_OJI: the facing desk fills the view with two colleagues holding their brown envelopes up against the daylight from the windows, then one of them grins and says something across the desk, then the other taps the edge of his envelope twice on the desktop and both of them laugh, while the shadow of the ceiling fan moves across the desks, as the room settles back to work",'office','pov_sit','Q',None,None,'warm'),
('C23','M2',"A_OJI: the shopping street fills the view with a colleague walking along beside them in the evening, then he turns his head towards them and says something with both hands full of shopping, then he laughs and goes on ahead of them left to right across the frame, while the awnings move in the wind, as the street fills with people coming home",'shotengai','pov_look','Q',None,None,'warm'),
]

# =====================================================================================
# MUC 3 — お茶くみは女性の仕事 (54-73)
# =====================================================================================
S += [
('D0','M3',"A_OJI: the office aisle runs away ahead of the view early in the morning with the desks still empty, then the view carries along it towards the tea room door, then stops where steam is coming out of the doorway, the whole move running left to right across the frame, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_look','Q',None,None),
('D1','M3',"A_JIMU, seen from behind at the counter, crouches at the gas ring in the tea room and turns the tap on under the kettle, then lifts the kettle onto the ring and lights it, then straightens up and wipes both hands on the apron, while steam gathers on the small window",'kyutou','medium','Q','C','A_JIMU standing at the lit ring with the kettle on it'),
('D2','M3',"A_OJI: the shelf of the tea room fills the view with teacups standing in a fixed row, then the view moves along the row from one end to the other, then stops on the one cup with a different pattern, while steam gathers on the small window",'kyutou','pov_look','Q','C',None),
('D3','M3',"A_OJI: the tea room counter fills the bottom of the view with the cups set out, then their own hand picks up the odd-patterned cup and turns it so the pattern faces out, then sets it back at the head of the row, while steam drifts across the small window",'kyutou','pov_hand','Q',None,None),
('D4','M3',"A_OJI: the tea room counter fills the view with a woman pouring hot water into the cups one by one along it, then she tips that water back into the teapot, then sets the pot down and stands with both hands on the counter edge, while steam drifts across the small window",'kyutou','pov_look','Q',None,None),
('D5','M3',"A_OJI: the counter fills the bottom of the view with the teapot standing on it, then their own hand lifts the lid and the steam comes up into the view, then sets the lid back down, while steam gathers on the small window",'kyutou','pov_hand','Q',None,None),
('D6','M3',"A_OJI: the office fills the view at three o'clock as a tray of cups comes along the aisle towards them, then the tray stops at their own desk, then one cup is set down on the desktop in front of the view, while the ceiling fan turns overhead and its shadow moves across the desks, as clerks all along the aisle keep working",'office','pov_look','Q',None,None),
('D7','M3',"A_JIMU, seen from behind and getting smaller, carries a tray at chest height the whole length of the office corridor at one even pace, then slows at the far door without stopping, then carries on through it and out of frame, while steam rises from the cups on the tray",'office','wide','Q',None,None),
('D8','M3',"A_OJI: the desk fills the bottom of the view with the teacup standing on it, then their own hand lifts the cup until its rim comes right up to the bottom edge of the view and tips it back to drink, then lowers it to the desk with the steam still curling off the surface, while the shadow of the ceiling fan moves across the desk",'office','pov','Q',None,None),
('D9','M3',"A_OJI: the tea room fills the view with the sink full of cups, then two hands that are not their own wash them one by one under the open tap, then stand one on the folded cloth to drain, while steam gathers on the small window",'kyutou','pov_look','Q',None,None),
('D10','M3',"A_OJI: the desk fills the bottom of the view with a teacup and a round lacquer saucer standing separately on it, then their own hand sets the cup down onto the middle of the saucer, then both hands lift the saucer level with the cup steady on it, while steam rises from the cup",'office','pov_hand','Q',None,None),
('D11','M3',"A_OJI: the office fills the view with the desks of the clerks, then the view turns slowly from the row of men on one side to the row of women on the other, then settles between them, while the ceiling fan turns overhead and its shadow moves across the desks, as both rows work without looking up",'office','pov_look','Q',None,None),
('D12','M3',"A_JIMU, seen from behind the whole time, clears the used cups from the desks into a tray the whole length of the aisle, then stops at the last desk and lifts the final cup, then carries the loaded tray away out of frame, while the ceiling fan turns overhead and its shadow moves across the desks, as the clerks go on working around her",'office','wide','Q',None,None),
('D13','M3',"A_IMA: the modern office fills the view with a machine on a low cabinet, then their own hand puts a paper cup under it and presses one button, then takes the filled cup away out of the bottom of the frame, while the curtain at the wide window stirs",'ima_office','pov_hand','Q',None,None),
('D14','M3',"A_OJI: the tea room fills the view at the end of the day with the cups back in their row on the shelf, then the view moves along the row to the odd-patterned cup, then the light on the small window goes dim, while steam fades from the small window",'kyutou','pov_look','Q',None,None),
('D15','M3',"A_OJI: the tea room door fills the view from the office side with steam coming out round it, then the view moves up to the doorway, then stops on the threshold, while steam drifts out across the doorway",'kyutou','pov_look','Q',None,None),
('D16','M3',"A_OJI: the gas ring fills the bottom of the view with the kettle standing on it, then their own hand turns the tap of the ring down a little, then withdraws out of the frame, while steam drifts across the small window",'kyutou','pov_hand','Q',None,None),
('D17','M3',"A_OJI: the office fills the view with the tray coming along the aisle, then the view follows it from desk to desk left to right across the frame, then stops where it reaches the head of the room, while the shadow of the ceiling fan moves across the desks, as the clerks keep working on both sides",'office','pov_look','Q',None,None),
('D18','M3',"A_OJI: the desk fills the bottom of the view with the cup and saucer set down on it, then their own finger turns the saucer so the cup stands square, then withdraws, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
('D19','M3',"A_OJI: the tea room fills the view with the plain dark apron hanging on its hook by the door, then the view holds on it, then turns to the empty counter beside it, while steam drifts across the small window",'kyutou','pov_look','Q',None,None),
('D20','M3',"A_OJI: the noticeboard fills the view with two printed sheets pinned side by side on it, then their own finger moves from the left sheet across to the right one, then stops there, while the shadow of the window frame moves across the board",'office','pov_hand','Q',None,None),
('D21','M3',"A_OJI: the desk island fills the view from a chair drawn in among the others at three o'clock, with a colleague at their own left elbow and another at their right and their own teacup standing on the desk in front of them, then the man across the island tells something with both hands up in the air, then the two beside them laugh and lean in over the desks, while steam rises from the cups, as the talk spreads along the room",'office','pov','Q','I','four of them sitting back round the island with teacups, laughing','warm'),
('D22','M3',"A_JIMU stops at the desk island with the loaded tray and sets a cup down at each place, then she says something that makes the men around the island laugh, then she straightens and carries the tray on along the aisle, while steam rises from the cups, as the talk goes on at the desks",'office','ots','Q','I',None,'warm'),
('D23','M3',"A_OJI: the office aisle runs away ahead of the view at three o'clock, then the view carries down it past the islands where colleagues stand talking in twos and threes with cups in their hands, then stops at the tea room door, the whole move running left to right across the frame, while steam drifts out of the doorway, as the talk goes on at every island",'office','pov_look','Q',None,None,'warm'),
]

# =====================================================================================
# CTA (74-76)
# =====================================================================================
S += [
('E0','CTA',"A_OJI: the far window of the office stands ahead of the view past the ends of the desks, then the view carries towards it between the two rows left to right across the frame, then stops at the sill with the town roofs showing beyond the glass, while the curtain at the window stirs, as clerks work at the desks on both sides",'office','pov_look','Q',None,None),
('E1','CTA',"A_OJI: the window fills the view with the town roofs beyond it, then their own hand comes into the frame and pushes the window open, then rests on the frame and stays there, while the curtain at the window stirs",'office','pov_stand','Q',None,None),
('E2','CTA',"A_OJI: the desk fills the bottom of the view with the open ledger on it, then their own two hands square the pages together, then rest flat on the closed cover, while the shadow of the ceiling fan moves across the desk",'office','pov_sit','Q',None,None),
('E3','CTA',"A_OJI: the desk fills the bottom of the view with the pen lying across the closed ledger, then their own hand stands the pen up in its holder, then rests flat on the ledger, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
]

# =====================================================================================
# MUC 4 — 上司の罵声は指導 (77-102)  ← muc DAI NHAT, dinh bai o day
# =====================================================================================
S += [
('F0','M4',"A_OJI: the office door stands open ahead of the view at the end of the corridor just after three, then the view carries through it into the room left to right across the frame, then stops as the far end comes clear, where a man has come round a desk and is standing over a seated one, while the shadow of the ceiling fan moves across the desks, as the nearer desks go on working",'office','pov_look','Q',None,None),
('F1','M4',"A_OJI: their own desk fills the bottom of the view with a set of papers on it, then a hand that is not their own comes into the frame and pushes the papers back across the desk, then the papers slide over the far edge and drop out of the bottom of the view, while the shadow of the ceiling fan moves across the desk",'office','pov_look','Q',None,None),
('F2','M4',"A_OJI: the floor beside the desk fills the view with the scattered papers on it, then their own two hands come down into the frame and gather them together, then square the edges against the floor",'office','pov_hand','Q',None,None),
('F3','M4',"A_OJI: the office fills the view from low beside the desk with every head in the room down over its work, then the view turns the whole length of the aisle, then comes back and nobody has looked up, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_hand','Q',None,None),
('F4','M4',"A_SENPAI sits at the next desk seen from behind and draws his chair half a pace back without looking round, then rests one hand flat on his own ledger, then goes on writing, while the ceiling fan turns overhead and its shadow moves across the desks, as the rest of the floor keeps working",'office','medium','Q',None,None),
('F5','M4',"A_OJI: the next desk fills the side of the view as a chair is drawn half a pace back, then the view holds on the hand resting flat on the ledger there, then turns away to their own desktop, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_look','Q',None,None),
('F6','M4',"A_OJI: the desk island fills the view with the black telephone ringing on it, then their own hand goes out towards it and takes up the receiver, then brings it towards the view, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_sit','Q',None,None),
('F7','M4',"A_OJI: the desk fills the bottom of the view with the telephone cradle on it, then their own hand sets the receiver back down onto it, then stays resting on the receiver and does not let go, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
('F8','M4',"A_OJI: the office fills the view with the rows of desks, then the view drops to their own hands flat on the desktop, then comes back up to the far end of the room where the standing man is still standing, while the ceiling fan turns overhead and its shadow moves across the desks, as the clerks around them work on",'office','pov_sit','Q',None,None),
('F9','M4',"A_OJI: the desktop fills the bottom of the view with an abacus on it, then their own fingers push all the beads back to one end in one stroke, then rest on the frame of it and stay, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
('F10','M4',"A_OJI: the office wall fills the view with the duty blackboard on it, then the view moves along the chalked columns of names, then stops on a column with no name written against it, while the light from the window moves across the board",'office','pov_look','Q',None,None),
('F11','M4',"A_OJI: the corridor outside the office runs away ahead of the view, then the view carries the whole length of it away from the room, then stops at the window at the end, the whole move running left to right across the frame, while the light from the tall window moves along the floor",'office_rouka','pov_look','Q',None,None),
('F12','M4',"A_OJI: the tall window at the end of the corridor fills the whole view with the roofs of the town beyond the glass, then their own left hand steadies against the frame as the right shoves the window open along its runner in one go, then the view tips back a little while the air comes in and the rolled sleeve flaps against their own forearm, while the smoke of a bathhouse chimney drifts out over the town",'office_rouka','pov','Q',None,None,('solo','ra hanh lang MOT MINH sau khi bi mang — mot minh la NOI DUNG cua muc 4')),
('F13','M4',"A_OJI: the ruled page of a printed law book fills the view on the desk, then their own finger moves down the printed article to the line about unpaid overtime, then stops under it and stays, while the light from the window moves across the page",'office','pov_hand','Q',None,None),
('F14','M4',"A_OJI: the printed page fills the whole view with the article number at the head of it, then the view holds still on the printed line, then moves down once to the date printed at the foot, while the light from the window moves across the page",'office','pov_hand','Q',None,None),
('F15','M4',"A_OJI: the office fills the view in the late evening with most of the desks dark and two lamps still on, then the view turns to the head of the room where one man is still at his desk, then turns back to their own papers, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_look','Q',None,None),
('F16','M4',"A_KACHOU stays at the desk at the head of the darkened office with one lamp on, seen from behind with his head bowed over the page, then turns a page of the ledger in front of him, then goes on reading without looking up, while the ceiling fan turns overhead and its shadow moves across the desks",'office','medium','Q',None,None),
('F17','M4',"A_OJI: their own desk fills the bottom of the view with the papers spread open again under the lamp, then their own hand moves the pen down one line, then stops and rests on the page, while the shadow of their own hand moves across the papers",'office','pov_sit','Q',None,None),
('F18','M4',"A_OJI: the wall clock at the end of the office fills the view with the hands well past the hour, then the view comes down to the row of dark desks, then stops on the one lamp still burning at the head of the room, while the ceiling fan turns overhead and its shadow moves across the desks",'office','pov_look','Q',None,None),
('F19','M4',"A_IMA: the modern office fills the view with a screen showing a plain internal notice, then their own hand moves the mouse and the page scrolls down once, then the hand withdraws from the frame, while the curtain at the wide window stirs",'ima_office','pov_hand','Q',None,None),
('F20','M4',"A_OJI: the noticeboard by the office door fills the view with a new printed sheet pinned up on it, then their own finger moves down to the line naming the consultation desk, then taps it once and withdraws, while the light from the window moves across the board",'office','pov_hand','Q',None,None),
('F21','M4',"A_OJI: the desk drawer fills the view pulled half open, then their own hand takes a folded cloth out of it and presses it once against their own forehead, then lays the cloth down on the desktop, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
('F22','M4',"A_OJI: the office fills the view with the clock showing half past seven in the evening, then the view comes down the wall to the row of dark desks, then stops on their own papers under the lamp, while the shadow of their own hand moves across the papers",'office','pov_sit','Q',None,None),
('F23','M4',"A_OJI: the corridor runs away ahead of the view with one light on at the far end, then the view carries the whole length of it towards that light, then stops at the window, the whole move running left to right across the frame, while the shadow of the window bars moves along the floor",'office_rouka','pov_look','Q',None,None),
('F24','M4',"A_OJI: the window at the end of the corridor fills the view with the lit town below it, then their own hand wipes a clear patch on the misted glass, then rests flat on the cold pane, while the curtain at the window stirs",'office_rouka','pov_stand','Q',None,None),
('F25','M4',"A_OJI: the desk of the next man fills the side of the view with his ledger open on it, then the view turns from his page across to their own, then settles on their own line, while the shadow of the ceiling fan moves across the desks, as the man beside them writes on without looking up",'office','pov_look','Q',None,None),
('F26','M4',"A_OJI: the office fills the view as the standing man returns to his own desk at the head of the room, then the view follows him along the aisle left to right across the frame, then stops as he sits down, while the shadow of the ceiling fan moves across the desks, as every head in the room stays down",'office','pov_look','Q',None,None),
('F27','M4',"A_OJI: their own two hands fill the bottom of the view flat on the desktop, then the fingers of one hand close slowly into the palm, then open out again and lie flat, while the shadow of the ceiling fan moves across the desk",'office','pov_hand','Q',None,None),
('F28','M4',"A_IMA: the modern office fills the view with a printed card standing on the desk, then their own hand turns the card round to read the line on it, then sets it back down facing out, while the curtain at the wide window stirs",'ima_office','pov_hand','Q',None,None),
('F29','M4',"A_OJI: their own desk fills the bottom of the view late in the afternoon, then a hand that is not their own pushes a teacup quietly across onto it, then the colleague it belongs to goes back to his own ledger without a word, while the shadow of the ceiling fan moves across the desk",'office','pov_sit','Q',None,None,'warm'),
('F30','M4',"A_OJI: the corridor outside the office fills the view with a colleague standing at the far window, then he turns his head towards them and says something short, then he gives a small nod and walks back towards the room left to right across the frame, while the shadow of the window bars moves along the floor",'office_rouka','pov_stand','Q',None,None,'warm'),
]

# =====================================================================================
# MUC 5 — 定年は五十五歳 (103-126)
# =====================================================================================
S += [
('G0','M5',"A_OJI: the aisle runs away ahead of the view towards the desk of the man in the grey work jacket, then the view carries the length of it left to right across the frame and draws up beside him, then tips down to his hands working on the ledger, while the shadow of the ceiling fan moves across the desks, as the floor works on around them",'office','pov_look','Q',None,None),
('G1','M5',"A_SENPAI leans across from the next desk and puts a ledger down open in front of the seated one, then points to a line in it with one finger, then straightens up and goes back to his own chair, while the ceiling fan turns overhead and its shadow moves across the desks, as the clerks around them keep working",'office','ots','Q','D','A_SENPAI standing between the two desks with his hand still out'),
('G2','M5',"A_OJI: their own desk fills the bottom of the view with the open ledger pushed across onto it, then a hand that is not their own comes in and points to one ruled line, then withdraws and leaves the ledger there",'office','pov_look','Q','D',None),
('G3','M5',"A_OJI: the office corner fills the view cleared of its desks, then the view turns across the pushed-back desks to the wrapped flowers lying on one of them, then settles on the flowers, while the light from the window moves across the desk, as people gather in around the cleared space",'soubetsu','pov_look','Q',None,None),
('G4','M5',"A_OJI: the desk in the cleared corner fills the bottom of the view with a large sheet of coloured paper on it, then their own hand turns the sheet over so the written side faces up, then moves down it once past the lines of handwriting, while the light from the window moves across the paper",'soubetsu','pov_hand','Q',None,None),
('G5','M5',"A_SENPAI, seen from behind over his own shoulder, takes the wrapped flowers up off the desk in both hands and holds them against his chest, then turns once towards the room, then walks away down the aisle and out of frame, while the light from the window moves across the desk, as the people round the cleared space raise their hands to clap",'soubetsu','wide','Q',None,None),
('G6','M5',"A_OJI: the aisle fills the view with the man walking away down it getting smaller, the flowers held against his chest, then he stops and turns his head back once, then goes on and out of the far door, while the light from the window moves along the floor, as the people on both sides go on clapping",'soubetsu','pov_look','Q',None,None),
('G7','M5',"A_OJI: the emptied desk fills the view with its drawers standing open and nothing in them, then their own hand comes into the frame and pushes one drawer shut, then rests on the closed drawer and stays, while the light from the window moves across the desk",'soubetsu','pov_hand','Q',None,None),
('G8','M5',"A_OJI: the inside of the midday train fills the view with the seats almost empty, then the view turns the whole length of the carriage, then settles on one man sitting alone by the window with flowers on his knee, while the whole carriage sways together on the rails",'densha_hiru','pov_look','Q',None,None),
('G9','M5',"A_SENPAI sits alone by the window of the almost empty midday train seen from behind over his shoulder, the wrapped flowers across his knees, then turns his face to the window, then settles back into the seat, while the light from the window moves along the empty seats",'densha_hiru','medium','Q',None,None),
('G10','M5',"A_OJI: the entrance hall of the house fills the view in the middle of the afternoon with the light coming through the frosted door, then the view turns to the empty corridor going into the house, then holds on it, while the shadow of the door frame moves across the step",'genkan','pov_look','Q',None,None),
('G11','M5',"A_OJI: the corridor of the house fills the view with a wall clock on it showing three, then the view holds on the hands, then drops to the empty corridor below it, while the light from the door moves along the floor",'genkan','pov_look','Q',None,None),
('G12','M5',"A_OJI: the step in the entrance hall fills the bottom of the view with one pair of work shoes set out on it, then their own hand comes into the frame and turns them to face the door, then withdraws and leaves them there",'genkan','pov_hand','Q',None,None),
('G13','M5',"A_OJI: the office fills the view with a new desk set a little apart from the rows, then the view turns from that desk to the row it used to stand in, then comes back to it, while the ceiling fan turns overhead and its shadow moves across the desks, as the clerks at the joined desks work on",'office','pov_look','Q',None,None),
('G14','M5',"A_OJI: the desk set a little apart from the rows fills the view with the man in the grey jacket at it, then the view holds as he writes one line into the ledger, then turns away to the joined desks in the rows, while the shadow of the ceiling fan moves across the desks, as the clerks at those desks keep working",'office','pov_look','Q',None,None),
('G15','M5',"A_OJI: the ruled page of a printed law book fills the view on the desk, then their own finger moves down the printed article to the line about the age of retirement, then stops under it and stays, while the light from the window moves across the page",'office','pov_hand','Q',None,None),
('G16','M5',"A_OJI: the printed page fills the whole view with two dates printed one under the other, then the view holds on the upper line, then moves down to the lower one and stays, while the light from the window moves across the page",'office','pov_hand','Q',None,None),
('G17','M5',"A_OJI: the office fills the view many years on with the desks rearranged and the fan gone, then the view turns the whole length of the room, then stops at the window at the far end, while the curtain at the window stirs, as clerks work on at every desk",'office','pov_look','Q',None,None),
('G18','M5',"A_OJI: their own two hands come into the frame over the emptied desktop, then set down a cloth cap and a folded newspaper on the corner of it, then take them up again and withdraw out of the bottom of the frame",'office','pov','Q',None,None),
('G19','M5',"A_OJI: the office aisle runs away ahead of the view towards the far door, then the view carries the whole length of it past the desks, then goes through the door, the whole move running left to right across the frame, while the curtain at the window stirs, as the clerks look up from the desks on both sides",'office','pov_look','Q',None,None),
('G20','M5',"A_OJI: the office fills the view with the man in the grey jacket emptying his desk drawer by drawer, then the view turns from the drawers to the bare desktop, then comes back to the last drawer standing open, while the shadow of the ceiling fan moves across the desks, as the clerks at the other desks work on",'office','pov_look','Q',None,None),
('G21','M5',"A_OJI: the cleared corner fills the view with the teacups set out on the pushed-back desks, then their own hand takes one of them up, then holds it still in front of the view, while the shadow of the window frame moves across the desks",'soubetsu','pov_hand','Q',None,None),
('G22','M5',"A_OJI: the coloured paper fills the view with the lines of handwriting on it, then the view moves down the sheet past the names, then stops at the blank space at the foot, while the shadow of their own hand moves across the paper",'soubetsu','pov_hand','Q',None,None),
('G23','M5',"A_OJI: the midday carriage fills the view with the empty seats along it, then the view turns to the window and the town going past, then comes back to the man sitting alone at the far end, while the whole carriage sways together on the rails",'densha_hiru','pov_look','Q',None,None),
('G24','M5',"A_OJI: the office fills the view years later with the desks rearranged, then their own hand rests on the back of the chair at the desk set apart from the rows, then lifts away, while the curtain at the window stirs",'office','pov_stand','Q',None,None),
('G25','M5',"A_OJI: the cleared corner fills the view with the whole floor gathered in a ring around it, then every one of them begins to clap together, then two of the nearest turn to each other smiling as they keep clapping, while the shadow of the window frame moves across the desks",'soubetsu','pov_stand','Q','K',"the whole floor standing in a ring, clapping",'warm'),
('G26','M5',"A_SENPAI stands in the middle of the cleared corner holding the wrapped flowers, then he bows deeply to the room, then he straightens and says a few words, while the shadow of the window frame moves across the desks, as the ring of colleagues goes on clapping",'soubetsu','ots','Q','K',"A_SENPAI standing with the flowers after his bow",'warm'),
('G27','M5',"A_OJI: the desk in front of them fills the view with the large sheet of coloured paper on it, then the colleague beside them writes a line and laughs at what he has written, then he slides the sheet along to the next desk, while the shadow of the window frame moves across the desks",'soubetsu','pov_sit','Q','K',None,'warm'),
('G28','M5',"A_OJI: the ring of colleagues fills the view and opens to make a path through it, then the view carries along that path between the clapping hands left to right across the frame, then stops where the wrapped flowers are waiting on the desk, while the shadow of the window frame moves across the desks, as the clapping goes on all round",'soubetsu','pov_look','Q',None,None,'warm'),
('G29','M5',"A_OJI: the long table at the send-off fills the view with the whole section sitting down both sides of it, then every one of them lifts a small glass together, then the man at the far end begins to sing and the rest clap along, while the lanterns sway a little over the doorway, as more people crowd in behind",'izakaya','pov_look','Q','L',"the whole table with their glasses lifted, one man singing",'warm'),
('G30','M5',"A_SENPAI sits at the head of the long table with the wrapped flowers beside him, then the two colleagues next to him fill his glass and say something, then all three of them laugh together, while the lanterns sway a little over the doorway, as the room stays full around them",'izakaya','ots','Q','L',None,'warm'),
]

# =====================================================================================
# KET (127-138)
# =====================================================================================
S += [
('L0','KET',"A_IMA: the modern office opens out ahead of the view past the low partitions, then the view carries between them left to right across the frame and comes to a stop at one desk, then their own hand reaches in and closes the laptop standing open on it, while the curtain at the wide window stirs",'ima_office','pov_walk','Q',None,None),
('L1','KET',"A_OJI: the Saturday platform fills the view empty under the canopy, then the view turns the whole length of it, then settles on the painted marks with nobody standing on them, while the wind moves along the platform",'eki_asa','pov_look','Q',None,None),
('L2','KET',"A_OJI: the desk fills the bottom of the view with a brown envelope lying on it, then their own hand comes into the frame and rests flat on the envelope, then lifts away and leaves it lying there",'office','pov_hand','Q',None,None),
('L3','KET',"A_OJI: the tea room shelf fills the view with the row of cups on it, then the view moves along the row to the odd-patterned one, then holds on it, while steam fades from the small window",'kyutou','pov_look','Q',None,None),
('L4','KET',"A_OJI: the floor beside the desk fills the view with one sheet of paper lying on it, then their own hand comes down and takes it up, then squares it and lifts it out of the top of the frame, while the shadow of the ceiling fan moves across the floor",'office','pov_hand','Q',None,None),
('L5','KET',"A_OJI: the cleared corner fills the view with the wrapped flowers lying on the desk, then the view holds on them, then turns away to the aisle, while the light from the window moves across the desk",'soubetsu','pov_look','Q',None,None),
('L6','KET',"A_OJI: the office aisle runs away ahead of the view between the rows of desks, then the view carries the whole length of it towards the window, then stops where the light comes across the floor, the whole move running left to right across the frame, while the curtain at the window stirs, as clerks work at the desks on both sides",'office','pov_look','Q',None,None),
('L7','KET',"A_OJI: the window of the office fills the view with the town roofs beyond it, then their own hand comes into the frame and rests on the frame of it, then stays there, while the curtain at the window stirs",'office','pov_stand','Q',None,None),
('L8','KET',"A_OJI: the desk fills the bottom of the view with the ledger closed on it, then their own two hands rest flat on the cover, then lift away and leave it there, while the shadow of the ceiling fan moves across the cover",'office','pov_sit','Q',None,None),
('L9','KET',"A_OJI: the corridor outside the office runs away ahead of the view towards the far window, then the view carries the whole length of it, then stops at the light coming in at the end, the whole move running left to right across the frame, while the light from the tall window moves along the floor",'office_rouka','pov_look','Q',None,None),
('L10','KET',"A_OJI: the platform fills the view with the rails beyond it, then the view turns from the empty platform to the rails going away, then holds on them, while the wind moves along the platform",'eki_asa','pov_look','Q',None,None),
('L11','KET',"A_OJI: the tall window at the far end of the room fills the view with the evening coming on outside, then their own hand draws the window to along its runner until it meets the frame, then turns the catch down onto it and lets go, while the curtain settles and hangs straight now the air has stopped",'office','pov','Q',None,None,('solo','canh KET, cuoi ngay — phong da vang, anh ta la nguoi cuoi cung')),
('L12','KET',"A_OJI: the tea room fills the view gone dark with the cups still in their row, then the view turns to the doorway and the office beyond it, then holds there, while steam fades from the small window",'kyutou','pov_look','Q',None,None),
('L13','KET',"A_OJI: the desk fills the bottom of the view wiped bare, then their own two hands rest flat on it, then lift away and leave nothing there, while the shadow of the ceiling fan moves across the desk",'office','pov_sit','Q',None,None),
('L14','KET',"A_OJI: the office at the end of the day fills the view with colleagues putting on their jackets, then two of them turn towards them and lift a hand in parting, then they go out through the far door left to right across the frame, while the curtain at the window stirs, as the desks empty on both sides",'office','pov_look','Q',None,None,'warm'),
]

CUT = set()
S = autochain(S, cut=CUT)

rows = build(S, P, C, crowd=CROWD)
n_red, n_warn = gate(rows, S, P, C,
                     interior={"office", "kyutou", "densha", "densha_hiru", "soubetsu",
                               "genkan", "ima_office"},
                     strict=True, crowd=CROWD)
act_report(S, C)
safe, risky, pct = linkage(S)
print("\nNOI AN TOAN: %d/%d moi noi cung boi canh co it nhat mot canh CHAT (%.0f%%)"
      % (safe, risky, pct))

# ⭐ ti le POV — yeu cau cua user la 90%
pov = sum(1 for x in S if str(x[4]).startswith("pov"))
print("POV: %d/%d = %.0f%%  (user chot 90%%)" % (pov, len(S), pov * 100 / len(S)))

OUTDIR = r"E:\Claude\Projects\youtube-jp-showa\06_VIDEO\14_showa-no-shokuba"
import os
os.makedirs(OUTDIR, exist_ok=True)
if n_red == 0:
    write_outputs(rows, OUTDIR)
    print("\nXUAT -> %s\\videogen_FLOW.txt | _TENFILE.txt | _BLOCKS.md" % OUTDIR)
else:
    print("\n[CHAN] %d loi do — KHONG xuat file. Sua roi chay lai." % n_red)
