# -*- coding: utf-8 -*-
"""Nguon cho STORYBOARD kinishinai bai 1 — BANG NHAN VAT + BOI CANH co dinh + moi shot anh:
(boi canh, hanh dong EN, file anh lo 0228 da khop). Shot the/chu hien dan lay tu SLIDES.
build: python tools/build_storyboard_01.py 01_kuchiguse-hitonome"""

CAST = [
    ("KIEKO (68)", "người kể, xưng 私", "a Japanese woman of 68, short soft silver hair in a neat bob, small pearl earrings, gentle round face, navy cardigan over a cream blouse"),
    ("YOUNG KIEKO (38)", "Kieko thập niên 1990, quầy 呉服", "a Japanese woman of 38, neat dark hair in a low bun, navy department-store uniform jacket, white blouse, small patterned scarf"),
    ("AYUMI (41)", "con gái Kieko", "a Japanese woman of 41, shoulder-length dark hair, beige sweater"),
    ("TAKESHI (44)", "con trai Kieko", "a Japanese man of 44, short hair, grey knit sweater"),
    ("REN (8)", "cháu nội", "a Japanese boy of 8, round face, yellow sweater"),
    ("NORIKO (70)", "hàng xóm", "a Japanese woman of 70, curly grey hair, green quilted vest"),
    ("SACHIKO (68)", "bạn 40 năm", "a Japanese woman of 68, short dark-grey hair, rust-orange sweater"),
    ("MICHIKO (64)", "em gái Kieko", "a Japanese woman of 64, grey hair tied back, cardigan, in her own kitchen"),
    ("DAISUKE (17)", "học sinh nhường ghế", "a Japanese high-school boy of 17 in a dark gakuran school uniform"),
    ("VIEWER (60s)", "「あなた」 ở 30s đầu — không phải Kieko", "an ordinary Japanese woman in her sixties, plain clothes"),
]

LOC = {
    "HOME": "INT. KIEKO'S HOUSE — tatami living room + kotatsu, kitchen at the back",
    "HOME_K": "INT. KIEKO'S HOUSE — KITCHEN",
    "VIEWER_HOME": "INT. VIEWER'S HOUSE",
    "DEPT": "INT. DEPARTMENT STORE — KIMONO COUNTER (1990s FLASHBACK)",
    "OFFICE80": "INT. OFFICE / IN-LAWS' HOME (1980s FLASHBACK)",
    "BUS": "INT. CITY BUS — SPRING",
    "STREET": "EXT. CITY STREET",
    "ARCADE": "EXT. SHOPPING ARCADE",
    "HALL": "INT. COMMUNITY HALL",
    "DANCHI": "EXT. APARTMENT COMPLEX COURTYARD",
    "CAFE": "INT. RETRO COFFEE SHOP",
    "PARK": "EXT. PARK / PATH",
    "TRAIN": "INT. TRAIN / RAILWAY PLATFORM — DECEMBER",
    "LAB": "INT./EXT. PSYCHOLOGY STUDY (ILLUSTRATIVE)",
    "SYMBOL": "SYMBOLIC — THE WATCHMAN (ANDON LANTERN)",
    "OBJECT": "INSERT — OBJECT",
    "MEMORY": "FLASHBACK — FADED PHOTOGRAPH LOOK",
    "POST": "INT. POST OFFICE / SUPERMARKET",
    "SISTER": "INT. MICHIKO'S KITCHEN — NIGHT",
}

# shot: (loc, action EN, file anh lo 0228 (tien to ten) hoac None = can gen, ghi chu)
S = {
0:  ("POST", "VIEWER bows again and again at a post-office counter, apologising to the clerk.", "Woman_bowing_at_post_office", ""),
1:  ("VIEWER_HOME", "Night. VIEWER lies awake in her futon, eyes open, replaying the day.", "Woman_lying_awake_in_bed", ""),
2:  ("VIEWER_HOME", "VIEWER sits up in the futon, one hand pressed to her chest.", "Woman_sitting_in_futon_worried", ""),
3:  ("DEPT", "YOUNG KIEKO bows deeply behind the kimono counter as customers pass.", "Woman_bowing_behind_kimono_counter", "lộ người kể 0:27"),
5:  ("SYMBOL", "A single andon lantern glows alone in a dark tatami room — the watchman, awake.", "Paper_lantern_in_dark_room", "motif 1/6"),
6:  ("OFFICE80", "YOUNG KIEKO bows to seniors at work; beside it, a young wife serving tea to in-laws.", "Japanese_woman_bowing_in_office", ""),
8:  ("HOME", "KIEKO and AYUMI sit at the same low table, eyes down, a quiet distance between them.", "Mother_and_daughter_sitting_toge", "câu hỏi treo"),
9:  ("HOME", "New Year's Day: the family around the kotatsu; an apron hangs by the kitchen door.", "Family_gathered_around_kotatsu_20261001032438", "hứa khối Tết"),
10: ("HOME", "KIEKO folds laundry in a sunny room, a small radio on the shelf.", "Woman_folding_laundry_indoors", "「ラジオのように」"),
12: ("STREET", "A young man hands a dropped glove back to KIEKO; she bows instead of smiling.", "Man_returning_glove_to_woman", ""),
13: ("DEPT", "YOUNG KIEKO at her kimono counter, 1990s colour.", "Woman_bowing_at_kimono_counter", ""),
14: ("OBJECT", "KIEKO's hands smooth used gift-wrap and fold it along the old creases into a drawer.", "Person_smoothing_wrapping_paper", ""),
15: ("DEPT", "YOUNG KIEKO bows to a customer before the customer can speak.", "Woman_bowing_at_store_counter", ""),
16: ("LAB", "A hand writes a thank-you letter with a fountain pen on plain paper.", "Hand_writing_letter_with_pen_20261001032437.jpg", "Kumar & Epley"),
17: ("SYMBOL", "The andon casts a shadow on the shoji far bigger than itself — the watchman overestimates.", "Paper_lantern_casting_shadow", "motif 2/6"),
18: ("STREET", "A man holds a door open, uneasy, while KIEKO keeps bowing and apologising.", "Man_holding_door_open", ""),
21: ("BUS", "Spring. DAISUKE stands to give his seat; KIEKO thanks him with a warm smile.", "Boy_giving_seat_on_bus", ""),
22: ("OBJECT", "An anpan bun in a small paper bag, held in KIEKO's hands outside the bakery.", "Hands_holding_Japanese_anpan_bun", ""),
23: ("STREET", "A crowded crossing seen from behind — many anonymous eyes.", "People_crossing_Japanese_street", ""),
25: ("ARCADE", "KIEKO in a new coat walks the arcade, glancing nervously at passers-by busy with their own phones.", "Woman_walking_down_shopping_street", ""),
26: ("OBJECT", "New eyeglasses beside a hand mirror on a small table.", "Eyeglasses_resting_on_small_table", ""),
27: ("LAB", "A university corridor between classes.", "Students_walking_in_university", "Gilovich 2000"),
28: ("LAB", "A student in a T-shirt with a big cartoon face walks into a classroom; almost nobody looks up.", "Student_entering_classroom", ""),
30: ("STREET", "KIEKO in plain grey walks the same grey street past bright shop windows without looking.", "Woman_walking_down_street", "このままだと"),
32: ("ARCADE", "Early summer. KIEKO in a floral blouse walks lightly; nobody pays attention.", "Woman_walking_in_shopping_arcade", ""),
33: ("HOME", "KIEKO puts on her shoes at the door, handbag ready, smiling — going out again.", "Woman_putting_on_shoes", "1→3 lần/tuần"),
34: ("DANCHI", "Neighbours chat politely by the rubbish point — the faces you meet every month.", "Neighbours_chatting_in_apartment", ""),
36: ("HALL", "Residents raise hands together; one raises hers last, slowly.", "Residents_raising_hands_at_meeting", ""),
37: ("MEMORY", "1970s: young housewives in aprons chatting in a danchi courtyard.", "Housewives_chatting_in_courtyard", ""),
40: ("HALL", "One person raises a hand for the other option; others begin to follow.", "Person_raising_hand_in_meeting", "Asch — người thứ hai"),
41: ("HALL", "Residents sit with arms folded, eyes lowered — disagreeing in silence.", "Residents_silently_disagreeing", ""),
42: ("HALL", "KIEKO at a gathering, smiling and nodding along, the smile a little stiff.", "Woman_smiling_at_neighborhood_ga", "このままだと"),
44: ("HALL", "Summer-festival meeting: KIEKO keeps her hands in her lap while others raise theirs.", "Woman_attending_community_meeting", ""),
45: ("HALL", "At the door, NORIKO leans in and whispers to KIEKO; both smile.", "Neighbour_whispering_to_woman", "「私もね、ほんとは…」"),
46: ("CAFE", "KIEKO and SACHIKO laugh over coffee.", "Two_friends_laughing_in_cafe", ""),
48: ("STREET", "Dusk. KIEKO walks home alone, replaying the conversation.", "Woman_walking_residential_street", ""),
49: ("SYMBOL", "The andon beside a blank notebook and a red pencil — marking every page.", "Lantern_glowing_beside_blank_not", "motif 3/6"),
50: ("LAB", "Two strangers chat on a park bench for the first time.", "Man_and_woman_chatting_on", "Boothby 2018"),
52: ("TRAIN", "SACHIKO on her own train home, smiling to herself.", "Woman_smiling_on_train", ""),
53: ("HOME", "KIEKO declines an invitation on the phone, then looks at the empty room.", "Woman_holding_phone_at_home", "このままだと"),
55: ("HOME", "Early autumn. KIEKO laughs on the phone by the window, red leaves outside.", "Woman_talking_on_phone_20261001032437", ""),
56: ("PARK", "KIEKO and SACHIKO walk an autumn path, planning next time.", "Two_women_walking_on_path", ""),
57: ("HOME", "Dusk. KIEKO alone at the window, hand on her chest — something still unsaid.", "Woman_standing_at_window", ""),
59: ("CAFE", "KIEKO's hands clasped tightly in her lap (held from shot 60 — one long shot).", None, "⏸ giữ ảnh ô 60 kéo dài (HOLD trong ingest_photos_01.py) — 2026-10-01 bỏ podcast, user chọn dùng ảnh dư"),
60: ("HOME", "KIEKO's hands clasped tightly in her lap.", "Woman_holding_hands_together", ""),
61: ("PARK", "On a bench, one woman quietly confides; the other listens warmly.", "Older_women_sitting_on_bench", "Bruk 2018"),
62: ("PARK", "The listener's warm, open face.", "Friend_smiling_in_soft_light", ""),
65: ("HALL", "A polite tea gathering: everyone smiling, every pair of eyes turned slightly away.", "Older_women_at_tea_gathering", "このままだと"),
67: ("HOME", "October night. KIEKO under a lamp, phone to her ear: 「最近ね、ちょっと、さみしいのよ」", "Woman_speaking_on_phone", ""),
68: ("SISTER", "MICHIKO on the phone in her kitchen, wiping tears while smiling.", "Woman_crying_while_smiling", ""),
70: ("SYMBOL", "The andon turned toward a dressing mirror; KIEKO looks at her own reflection.", "Woman_looking_in_mirror", "motif 4/6"),
72: ("HALL", "KIEKO holds a blank hula-class flyer outside the centre, then shakes her head at herself.", "Woman_holding_flyer_at_center", ""),
73: ("MEMORY", "1960s: a teenage girl in formal seiza before strict elders.", "Girl_sitting_before_elders", ""),
74: ("PARK", "An older couple walks an autumn park at their own pace.", "Older_couple_walking_in_park", "Carstensen"),
76: ("OBJECT", "A row of closed boxes on a shelf; one lid slightly open, light inside.", "Box_opening_with_light_inside", "このままだと"),
78: ("TRAIN", "December. KIEKO on the platform with a small suitcase, excited.", "Woman_standing_on_railway_platform", ""),
79: ("PARK", "KIEKO walks alone up a quiet village path — a year of letting go.", "Elderly_woman_walking_on_path", "ảnh dư thay ảnh 2 người ăn cơm hộp (sai 「ひとり旅」); khớp câu 2 của ô"),
80: ("HOME_K", "An apron hangs on a hook by the dim kitchen doorway.", "Kitchen_apron_hanging_on_hook", "cliffhanger mục 7"),
82: ("HOME_K", "KIEKO alone in the kitchen with a cup, the lantern glowing, laughter beyond.", "Woman_listening_near_paper_lantern", ""),
83: ("HOME", "Dinner: TAKESHI and his father argue; KIEKO bows her head to calm them.", "Family_arguing_at_dinner_table_20261001032435.jpg", ""),
84: ("HOME", "At the same table, the mother keeps her head down, hands clasped, enduring — and it shows.", "Family_arguing_at_dinner_table_20261001032435_2", "ảnh dư (bản 2 của ô 83); ⚠️ mất motif đèn 5/6"),
85: ("LAB", "An empty study room: two chairs facing across a small table.", "Empty_psychology_study_room_chairs", "Butler/Gross 2003"),
86: ("LAB", "A woman keeps a carefully blank face while talking; the other leans back, uneasy.", "Woman_talking_with_uneasy_person", ""),
87: ("HOME", "AYUMI at the kotatsu glances uneasily toward her mother in the kitchen.", "Woman_glancing_toward_kitchen", ""),
90: ("HOME", "KIEKO on the phone saying no politely, her shoulders dropping.", "Woman_talking_on_phone_home", ""),
91: ("HOME_K", "KIEKO and NORIKO laugh freely at the kitchen table over tea.", "Two_older_women_laughing_at", ""),
92: ("HOME", "New Year's Day: a shimekazari on the door; AYUMI's and TAKESHI's families arrive.", "Family_arriving_at_Japanese_house", "KHỐI TẾT"),
93: ("HOME", "The family around the kotatsu; KIEKO in an apron at the kitchen counter behind them.", "Family_gathered_around_kotatsu_20261001032435.jpg", ""),
94: ("HOME_K", "KIEKO's hands ladle ozoni into lacquer bowls, steam rising.", "Woman_ladling_soup_into_bowls", ""),
95: ("HOME", "New Year photos across the decades — in every one, the mother stands at the edge.", "Photographs_of_New_Year_gatherings", ""),
96: ("HOME_K", "KIEKO turns toward the sink — and stops halfway.", "Woman_turning_toward_sink", ""),
97: ("SYMBOL", "The andon glows softly in the room; the watchman's voice.", "Lantern_glowing_in_tatami_room", "motif 6/6 (ảnh chưa có Kieko — tạm nhận)"),
99: ("HOME", "KIEKO unties her apron and slips under the kotatsu beside her family.", "Woman_sitting_at_kotatsu_table", ""),
100: ("HOME", "REN stares up, wide-eyed: 「おばあちゃんって、座れるんだ」", "Grandchild_staring_surprised", ""),
101: ("HOME", "The whole family bursts into laughter around the kotatsu.", "Japanese_family_around_kotatsu", ""),
103: ("HOME", "KIEKO at the kotatsu, looking at her family in quiet realisation; the kitchen empty behind.", "Woman_sitting_at_kotatsu_20261001032435.jpg", ""),
105: ("HOME", "Mikan peels and an old album on the kotatsu; KIEKO and AYUMI turn a page.", "Women_turning_photo_album_page", ""),
106: ("SYMBOL", "Dawn. The andon's light turned low, pale morning through the shoji — the watchman at rest.", "Paper_lantern_glowing_at_dawn", "motif kết"),
108: ("HOME", "The whole family around the kotatsu — KIEKO sitting in the middle this time.", "Family_gathered_around_kotatsu_20261001032435_2", "CẢNH KẾT"),
110: ("OBJECT", "A cup of green tea by a sunny window, the curtain moving.", "Cup_of_green_tea", ""),
111: ("PARK", "Morning. KIEKO walks lightly along a sunny path, shoulders relaxed, seen from behind.", "Older_woman_walking_on_path", ""),
}
