# -*- coding: utf-8 -*-
"""Bo sung phan A len ngan sach 8s/clip: HOOK 8->11, N2 35->50, KAISOU 13->19.
Moi phan tu: (after_id, scene) — chen NGAY SAU canh co id do."""
INS_A = [
# ── HOOK +3 ──
('H2', ('H2b','HOOK',"A_CHIZURU: the crowded floor fills the view from the reception table, then the view turns slowly right to left across the frame along the rows of bedding, then stops on the far corner where a machine light glows, while the wind drives the rain down the high windows, as families all across the floor settle their bedding",'uketsuke','pov_look','Q',None,None)),
('H5', ('H5b','HOOK',"A_CHIZURU: the small oxygen machine fills the bottom of the view beside the blanket, then its indicator light glows steadily green, then an old hand comes to rest on the casing above it, while the shadow of the blanket lies still across his knees",'sumi','pov_hand','Q',None,None)),
('H7', ('H7b','HOOK',"A_CHIZURU: the reception table fills the view with A_MAGO turning away from it, then he walks away from the camera back down the hall, then he is lost among the rows of bedding, while the shadows under the table shift as the fluorescent light flickers overhead, as the people waiting behind close up the gap he leaves",'uketsuke','pov_look','Q',None,None)),
# ── N2 +15 ──
('B01',('B01b','N2',"A_CHIZURU: the fluorescent tube of the walkway fills the top of the view, then it flickers once and steadies, then the view comes down to the boards and the narrow blue sheet, while the wind blows the rain past the doorway beyond",'rouka','pov_look','Q',None,None)),
('B04',('B04b','N2',"A_CHIZURU: the hall fills the view from the doorway with the boxes of supplies stacked along the wall, then the view carries towards them left to right across the frame, then stops where a woman is counting folded blankets, while the shadows of the roof beams lie across the floor, as families pass behind her with bedding in their arms",'taiikukan','pov_walk','Q',None,None)),
('B06',('B06b','N2',"A_SETSUKO stands at the reception table and speaks to two evacuees waiting in front of it, filmed over their shoulders so her face is half turned away, then she points along the hall with one hand, then she looks back down at the ledger, while the shadows under the table shift as the fluorescent light flickers overhead, as more people join the line behind them",'uketsuke','ots','Q',None,None)),
('B11',('B11b','N2',"A_CHIZURU: the ruled column of the ledger fills the bottom of the view with a row of names down it, then their own finger moves down the column away from the camera, then stops at the last line, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_hand','Q',None,None)),
('B14',('B14b','N2',"A_CHIZURU: a plastic box of pens and pencils stands on the reception table in the bottom of the view, then their own hand lifts one pen clear of it, then sets it back down among the others, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_hand','Q',None,None)),
('B21',('B21b','N2',"A_SETSUKO stands in front of the stack of blankets and lifts one folded blanket off the top of it, then she holds it out towards the person with the phone, then lowers it back onto the stack, while the shadows of the roof beams lie across the floor, as families on the sheets around her go on with their bedding",'taiikukan','wide','Q',None,None)),
('B23',('B23b','N2',"A_ICHINOSE, seen from behind the whole time, sits against the wall with A_MAGO crouched beside him, then A_MAGO leans in and speaks close to him, then the old man lifts one hand a little and lets it fall, while the shadow of the blanket lies still across his knees, as the few people near the corner keep to themselves",'sumi','behind','Q',None,None)),
('B24',('B24b','N2',"A_CHIZURU: the cable running from the plug socket fills the bottom of the view across the boards, then the view follows it away from the camera along the floor, then stops where it climbs into a stack of equipment, while the shadows of the roof beams lie across the floor",'taiikukan','pov_look','Q',None,None)),
('B31',('B31b','N2',"A_CHIZURU: the line of people waiting at the reception table fills the view, then the person at the front of it steps aside, then the next moves up to the table, while the shadows under the table shift as the fluorescent light flickers overhead, as the line closes up behind them",'uketsuke','pov_look','Q',None,None)),
('B35',('B35b','N2',"A_CHIZURU: the far corner fills the view with the old man and A_MAGO sitting together, then A_MAGO looks up towards the middle of the hall, then he looks back down at the machine, while the shadow of the blanket lies still across his knees, as the corner stays quiet around them",'sumi','pov_look','Q',None,None)),
('B41',('B41b','N2',"A_CHIZURU: the blanket lies over the old knees in the bottom of the view, then an old hand smooths it once away from the camera, then rests flat on top of it, while the shadow of the blanket lies still across his knees",'sumi','pov_hand','Q',None,None)),
('B44',('B44b','N2',"A_CHIZURU: the aisle between two rows of bedding runs away ahead of the view, then heads turn up from the sheets on both sides towards the camera side, then they turn back down again one by one, while the shadows of the roof beams lie across the floor, as the whole row settles",'taiikukan','pov_look','Q',None,None)),
('B50',('B50b','N2',"A_CHIZURU: the sheet across the aisle fills the view with a pair of small shoes set side by side at the edge of it, then the blanket beside them stirs once, then settles flat again, while the shadows of the roof beams lie across the floor",'taiikukan','pov_look','Q',None,None)),
('B52',('B52b','N2',"A_HAHA sits on the sheet with her back to the camera and draws the blanket up over the bedding, then she smooths it flat, then she sits back on her heels and stays there, while the shadows of the roof beams lie across the floor, as the families on both sides lie still",'taiikukan','behind','Q',None,None)),
('B61',('B61b','N2',"A_CHIZURU: the rows of bedding fill the view as people begin gathering their bags, then a whole row stands up together, then they start away towards the stairs left to right across the frame, while the shadows of the roof beams lie across the floor, as more families rise on both sides",'taiikukan','pov_look','Q',None,None)),
('B62',('B62b','N2',"the line of evacuees climbs the concrete stairs at the side of the hall, filmed from behind the whole time, then the front of the line reaches the turn, then it goes on up out of sight, while the shadows of the roof beams lie across the floor, as more people press in at the foot of the stairs",'taiikukan','behind','Q',None,None)),
('B63',('B63b','N2',"A_CHIZURU: the emptying corner fills the view with the old man alone against the wall, then the last of his neighbours picks up a bag and goes, then the corner is left with only him and the machine, while the shadow of the blanket lies still across his knees",'sumi','pov_look','Q',None,None)),
# ── KAISOU +6 ──
('K02',('K02b','KAISOU',"the boards of the hall of the old night fill the frame with a towel and a cup left on them, then the light moves across the cup, then a draught stirs the edge of the towel, while the wind drives the rain down the high windows",'taiikukan','still','Q',None,None)),
('K04',('K04b','KAISOU',"the far wall of the old hall fills the view from low down with the empty place along it, then a figure comes into the far edge of the frame and kneels there, then stays down without moving, while the shadow from the high windows shifts a little, as the rest of the floor lies still",'taiikukan','low','Q',None,None)),
('K05',('K05b','KAISOU',"the light over the gymnasium doors burns in the rain with nobody under it, then the rain drives across the light, then the beam of it reaches the standing water, while the wind drives the rain across the light over the door",'soto','still','Q',None,None)),
('K07',('K07b','KAISOU',"headlights swing across the wet road outside the school gate and stop short of the standing water, then the light holds on the water, then it backs away the way it came, while the wind drives the rain across the light over the door",'soto','still','Q',None,None)),
('K09',('K09b','KAISOU',"A_CHIZURU: the closed blue booklet lies on their own lap in the bottom of the view, then their own hand lifts the cover a finger's width, then lets it fall shut again, while the shadow of the doorframe lies across the boards",'rouka','pov_hand','Q',None,None)),
('K10',('K10b','KAISOU',"A_CHIZURU: the narrow blue sheet and the boards fill the bottom of the view, then the view turns slowly left to right across the frame to the gap under the double door, then settles on the wet line the rain has made there, while the wind pushes the rain in under the door",'rouka','pov_look','Q',None,None)),
]
