# -*- coding: utf-8 -*-
"""Phan A cua S: HOOK (8) + N2 (35) + KAISOU (13)."""
SA = []

# ══ HOOK 0:00–1:30 — 8 clip ══
SA += [
('H0','HOOK',"A_CHIZURU: the reception table fills the bottom of the view with an open ruled ledger on it, then a hand in a navy sleeve comes into the frame and rests a pencil on the open page, then draws back and leaves the pencil lying across the column, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_hand','Q','H',"a pencil lying across the open ledger on the reception table"),
('H1','HOOK',"A_CHIZURU: the same open ledger fills the bottom of the view with the pencil lying across it, then their own hand turns the ledger a little towards them, then stops with the ruled column facing up, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_hand','Q','H',None),
('H2','HOOK',"A_CHIZURU: the high wall of the gymnasium fills the top of the view with a small security camera bracketed up near the roof, then the view comes down the wall to the crowded floor of blue sheets and blankets, then settles on the rows of families, while the wind drives the rain down the high windows, as people all across the floor settle their bedding",'uketsuke','pov_look','Q',None,None),
('H3','HOOK',"A_SETSUKO stands at the reception table with the ledger in front of her and speaks towards the camera side without looking up, then closes the ledger with one hand, then tucks it under her arm and turns away towards the hall, while the shadows under the table shift as the fluorescent light flickers overhead, as evacuees keep moving past behind her",'uketsuke','ots','Q',None,None),
('H4','HOOK',"A_CHIZURU: the far corner of the hall opens out ahead of the view past the rows of bedding, then the view carries towards that corner left to right across the frame, then stops where an old man sits with a blanket over his knees beside a small oxygen machine, while the wind drives the rain down the high windows, as families on both sides sit among their bedding",'sumi','pov_look','Q','I',"the old man sitting with the oxygen machine beside him"),
('H5','HOOK',"A_ICHINOSE, seen from behind the whole time, sits with the blanket over his knees, then lifts one hand and rests it on the top of the small oxygen machine beside him, then leaves it there without moving, while the shadow of the blanket lies still across his knees, as a few people move about in the background of the corner",'sumi','behind','Q','I',None),
('H6','HOOK',"A_CHIZURU: the reception table fills the view with A_MAGO standing at it with his back to the camera, then he bows his head to the woman behind the table, then straightens and bows again, while the shadows under the table shift as the fluorescent light flickers overhead, as the evacuees waiting behind him look away",'uketsuke','pov_look','Q','J',"A_MAGO standing at the reception table with his head bowed"),
('H7','HOOK',"A_CHIZURU: the same reception table fills the view with A_MAGO still standing there, then he bows his head a third time, then stays bent over while nobody behind the table moves, while the shadows under the table shift as the fluorescent light flickers overhead, as the people waiting behind him turn their faces away",'uketsuke','pov_look','Q','J',None),
]

# ══ N2 1:30–8:10 — 35 clip ══
# beat 1 (22:40) mat CHO
SA += [
('B00','N2',"A_CHIZURU: their own knees and the edge of a narrow blue plastic sheet fill the bottom of the view in the walkway, then their own hands come up and rest flat on their knees, then settle there without moving, while the wind blows the rain past the doorway beyond",'rouka','pov_sit','Q',None,None),
('B01','N2',"A_CHIZURU: the double door of the walkway fills the view with a finger-wide gap along the bottom of it, then a thin drift of rain comes in under the door across the boards, then it reaches the edge of the blue sheet, while the wind pushes the rain in under the door",'rouka','pov_look','Q',None,None),
('B02','N2',"A_CHIZURU: the narrow walkway runs away ahead of the view with a single strip of blue plastic sheet laid against the wall, then the view carries along it towards the hall doorway left to right across the frame, then stops short of the doorway, while the wind blows the rain past the doorway beyond",'rouka','pov_look','Q','K',"the view stopped at the walkway doorway looking into the hall"),
('B03','N2',"A_CHIZURU: the hall opens out ahead of the view from the walkway doorway, then the rows of bedding run away from the camera to the far wall, then the view settles on the crowded middle of the floor, while the shadows of the roof beams lie across the floor, as families all across the floor settle for the night",'rouka','pov_look','Q','K',None),
('B04','N2',"A_SETSUKO walks the length of the hall between the rows of bedding, seen from behind the whole time, then stops at the middle of the floor, then turns to look back along the rows, while the shadows of the roof beams lie across the floor, as families on both sides look up as she passes",'taiikukan','behind','Q',None,None),
('B05','N2',"A_CHIZURU: a hand-lettered card on a cord hangs in the middle of the view against a navy jacket, then it swings a little as the person wearing it moves, then settles flat again, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_look','Q',None,None),
('B06','N2',"A_CHIZURU: a yellow cloth armband fills the middle of the view on a navy sleeve, then the arm lifts and points away down the hall, then comes back down to the table, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_look','Q',None,None),
]
# beat 2 (23:20) mat TEN
SA += [
('B10','N2',"A_CHIZURU: the reception table fills the view again as the view comes back to it along the hall, then it stops at the near edge of the table, then the open ledger comes into the bottom of the frame, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_walk','Q','L',"the view stopped at the near edge of the reception table"),
('B11','N2',"A_CHIZURU: the open ledger lies in the bottom of the view with the ruled column facing up, then their own finger comes into the frame and points at one line of it, then withdraws to the edge of the table, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_hand','Q','L',None),
('B12','N2',"A_SETSUKO, seen from behind the whole time, stands at the reception table over the open ledger, then rubs the side of her thumb once along a line on the page, then writes above it and steps back from the table, while the shadows under the table shift as the fluorescent light flickers overhead, as evacuees pass along behind her",'uketsuke','behind','Q','M',"A_SETSUKO stepping back from the open ledger on the table"),
('B13','N2',"A_CHIZURU: the open ledger fills the bottom of the view on the table, then their own hand comes into the frame and stops short of the page without touching it, then withdraws to the edge of the table, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_hand','Q','M',None),
('B14','N2',"A_CHIZURU: the page of the ledger fills the bottom of the view, then a second name is written in above a rubbed-out line, then the pen is lifted away and the page left as it is, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_hand','Q',None,None),
('B15','N2',"A_CHIZURU: the walkway runs away ahead of the view from the hall doorway, then the view carries back along it away from the camera side, then stops at the strip of blue sheet by the far door, while the wind blows the rain past the doorway beyond",'rouka','pov_walk','Q',None,None),
]
# beat 3 (23:50) quay video thanh tich
SA += [
('B20','N2',"A_SETSUKO stands in the middle of the hall in front of a stack of folded blankets and straightens her jacket, then squares her shoulders to a phone held up by someone off to one side, then holds still for it with her chin lifted, while the shadows of the roof beams lie across the floor, as families on the sheets around her go on with their bedding",'taiikukan','wide','Q','N',"A_SETSUKO standing squared up in front of the stack of blankets"),
('B21','N2',"A_SETSUKO stands in front of the stack of blankets with her chin lifted, then she lowers her shoulders and shakes her head once at the person holding the phone, then squares up and holds the same pose again, while the shadows of the roof beams lie across the floor, as families on the sheets around her go on with their bedding",'taiikukan','wide','Q','N',None),
('B22','N2',"A_CHIZURU: the stack of blankets fills the middle of the view with the woman in the navy jacket posed in front of it, then the view turns slowly away from her right to left across the frame towards the far corner of the hall, then settles on the old man still waiting beside the plug socket, while the shadows of the roof beams lie across the floor, as people cross the floor between them",'taiikukan','pov_look','Q',None,None),
('B23','N2',"A_CHIZURU: the far corner fills the view with the old man sitting against the wall beside the plug socket, then A_MAGO crouches down beside him and says something, then straightens and looks off towards the middle of the hall, while the shadow of the blanket lies still across his knees, as the few people near the corner keep to themselves",'sumi','pov_look','Q',None,None),
('B24','N2',"A_CHIZURU: the plug socket low on the wall fills the bottom of the view with two plugs already in it, then a cable is drawn taut across the floor away from the camera, then it goes out of the frame towards the middle of the hall, while the shadow of the cylinder shifts at the side of the frame",'sumi','pov_hand','Q',None,None),
]
# beat 4 (0:15) mat TIENG NOI
SA += [
('B30','N2',"A_CHIZURU: the hall runs away ahead of the view from the corner towards the reception table, then the view carries along the rows of bedding left to right across the frame, then stops at the table, while the shadows of the roof beams lie across the floor, as families draw their bedding in as the view passes",'taiikukan','pov_walk','Q','P',"the view stopped at the reception table"),
('B31','N2',"A_CHIZURU: the reception table fills the view with the woman in the navy jacket on the far side of it, then she lifts one hand flat towards the camera side without looking up, then lowers it to the ledger again, while the shadows under the table shift as the fluorescent light flickers overhead, as the evacuees waiting behind go quiet",'uketsuke','pov_look','Q','P',None),
('B32','N2',"A_CHIZURU: the reception table fills the bottom of the view with a black corded telephone standing on it, then their own hand comes to rest on the table beside the telephone without lifting it, then draws back to the edge of the table, while the shadows under the table shift as the fluorescent light flickers overhead",'uketsuke','pov_hand','Q',None,None),
('B33','N2',"A_CHIZURU: the steel store door fills the view with a padlock hanging through the hasp, then the view moves a little closer so the shut padlock fills the middle, then holds on it, while the wind drives the rain against the roof outside",'souko','pov_look','Q','R',"the shut padlock filling the middle of the view"),
('B34','N2',"A_CHIZURU: the distribution board beside the store door fills the view with its cover closed, then their own hand rests flat on the closed cover, then comes away and hangs at the edge of the frame, while the wind drives the rain against the roof outside",'souko','pov_hand','Q','R',None),
('B35','N2',"A_CHIZURU: A_MAGO walks away from the camera down the middle of the hall towards the far corner, then he slows near the corner, then he sits down on the sheet beside the old man, while the shadows of the roof beams lie across the floor, as families on both sides lie still",'taiikukan','pov_look','Q',None,None),
]
# beat 5 (1:00) mat UY TIN
SA += [
('B40','N2',"A_CHIZURU: their own arms fill the bottom of the view holding a folded grey blanket, then the view carries between the rows of bedding towards the far corner left to right across the frame, then stops beside the old place and the blanket goes down onto the sheet, while the shadows of the roof beams lie across the floor, as families on both sides look up from their bedding",'taiikukan','pov_walk','Q','T',"the folded grey blanket left on the sheet in the far corner"),
('B41','N2',"A_CHIZURU: the folded grey blanket lies on the sheet in the bottom of the view, then an old hand comes into the frame and draws it in over his knees, then settles flat on top of it, while the shadow of the blanket lies still across his knees",'sumi','pov_hand','Q','T',None),
('B42','N2',"A_SETSUKO stands in the middle of the hall holding a microphone and speaks out across the floor, then lowers the microphone to her side, then looks steadily towards the far side of the hall, while the shadows of the roof beams lie across the floor, as heads come up from the bedding all across the floor and turn the same way",'taiikukan','wide','Q','U',"A_SETSUKO standing with the microphone lowered to her side"),
('B43','N2',"A_CHIZURU: the rows of bedding fill the view from the walkway doorway, then a couple on the nearest sheet draw their bags in towards themselves, then settle again without looking up, while the wind drives the rain down the high windows, as the families beyond them go quiet",'taiikukan','pov_look','Q','U',None),
('B44','N2',"A_CHIZURU: the nearest sheet fills the bottom of the view with two bags standing on it, then the bags are lifted and set down again a hand's width further away, then a hand is laid flat on top of them, while the shadows of the roof beams lie across the floor",'taiikukan','pov_look','Q',None,None),
]
# beat 6 (1:40) co be + me
SA += [
('B50','N2',"A_CHIZURU: a sheet across the aisle fills the view with A_HAHA sitting awake beside a made-up sleeping place, then she turns to look down the hall away from the camera, then turns back to the bedding, while the shadows of the roof beams lie across the floor, as the families on both sides lie still",'taiikukan','pov_look','Q','V',"A_HAHA sitting awake beside the made-up bedding"),
('B51','N2',"A_HAHA gets up from the sheet and walks away from the camera towards the reception table, filmed from behind the whole time, then she stops at the table, then she turns and comes back the way she went, while the shadows of the roof beams lie across the floor, as other families lie still on both sides",'taiikukan','behind','Q','V',None),
('B52','N2',"A_CHIZURU: the sheet across the aisle fills the view with A_HAHA crouched over the bedding, then she leans down and speaks low over it, then she looks up once towards the walkway side, while the shadows of the roof beams lie across the floor, as the families around them lie still",'taiikukan','pov_look','Q',None,None),
('B53','N2',"A_CHIZURU: their own hands lie flat on their own knees in the bottom of the view, then the fingers draw together slowly, then rest still again, while the wind blows the rain past the doorway beyond",'rouka','pov_sit','Q',None,None),
]
# beat 7 (2:10) mat AN TOAN
SA += [
('B60','N2',"A_CHIZURU: the hall fills the view with the rows of families lying and sitting, then the view turns up across the frame to the high windows with the rain running down them, then comes back down to the floor, while the shadows of the roof beams lie across the floor, as people settle for the night across the whole floor",'taiikukan','pov_look','Q',None,None),
('B61','N2',"A_SETSUKO stands at the middle of the floor with the microphone up and speaks out over the rows, filmed from high up so her face is not readable, then she lowers the microphone, then she turns towards the stairs at the side of the hall, while the shadows of the roof beams lie across the floor, as families all over the floor begin gathering their bags",'taiikukan','high','Q',None,None),
('B62','N2',"A_CHIZURU: the foot of a flight of concrete stairs fills the view at the side of the hall, then a line of people begins to climb it away from the camera, then the line goes on up out of the top of the frame, while the shadows of the roof beams lie across the floor, as more people gather at the foot of the stairs",'taiikukan','pov_look','Q',None,None),
('B63','N2',"A_CHIZURU: the far corner fills the view with the old man still sitting against the wall, then the people around him get up and move away towards the stairs, then he stays where he is with the machine beside him, while the shadow of the blanket lies still across his knees, as the corner empties around him",'sumi','pov_look','Q',None,None),
('B64','N2',"A_CHIZURU: the front doors of the gymnasium stand open at the far end of the view and A_GYOSHA steps in, then he stops just inside and looks along the hall towards the camera side, then he bows his head a little, while the wind blows the rain in behind him, as evacuees near the door turn to look at him",'taiikukan','pov_look','Q',None,None),
]

# ══ KAISOU 8:10–10:40 — 13 clip ══
SA += [
('K00','KAISOU',"the same gymnasium hall on a night twelve years earlier, the same blue sheets on the floor, filmed from high up under the roof so that no face is readable, then the whole floor of bedding lies still below, then one place at the far wall stays empty with a pair of plastic sandals set neatly beside it, while the wind drives the rain down the high windows",'taiikukan','high','Q','W',"the empty place at the far wall with the sandals beside it"),
('K01','KAISOU',"the same empty place at the far wall fills the view, a pair of plastic sandals set neatly side by side on the boards, then the view moves slowly down towards them, then stops just above them, while the shadow from the high windows shifts a little",'taiikukan','low','Q','W',None),
('K02','KAISOU',"a folded blanket and a cushion lie on the boards at the far wall with nobody on them, then the light from the high windows moves across the blanket, then it reaches the edge of the sandals, while the shadow from the high windows shifts a little",'taiikukan','still','Q',None,None),
('K03','KAISOU',"an armband lies on the boards of the hall beside a folded towel, then the light moves across it, then a draught lifts one corner of the towel and lays it down again, while the wind drives the rain down the high windows",'taiikukan','still','Q',None,None),
('K04','KAISOU',"the rows of bedding of the old night fill the frame from high up under the roof, then one figure moves slowly along the far side of the hall, then reaches the far wall and stops there, while the wind drives the rain down the high windows, as the rest of the floor lies still",'taiikukan','high','Q',None,None),
('K05','KAISOU',"the concrete apron outside the doors at night in heavy rain, empty, the light over the door shining on the wet ground, then the rain drives across the light, then a puddle at the near edge breaks up in the wind",'soto','still','Q',None,None),
('K06','KAISOU',"the wet road outside the school gate at night with water standing across it, then the water moves in the wind, then it laps up over the kerb, while the wind drives the rain across the light over the door",'soto','still','Q',None,None),
('K07','KAISOU',"the doors of the gymnasium from outside in the rain, shut, with light in the gap between them, then the light in the gap goes on burning, then rain runs down the face of the doors from top to bottom across the frame, while the wind drives the rain across the light over the door",'soto','still','Q',None,None),
('K08','KAISOU',"A_CHIZURU: their own hands fill the bottom of the view holding a thin blue booklet closed on their lap, then their own thumb runs left to right along the closed edge of it once, then stops without opening it, while the shadow of the doorframe lies across the boards",'rouka','pov_sit','Q',None,None),
('K09','KAISOU',"A_CHIZURU: the blue booklet lies closed on their own lap in the bottom of the view, then their own hand turns it over so the back cover faces up, then rests flat on top of it, while the shadow of the doorframe lies across the boards",'rouka','pov_hand','Q',None,None),
('K10','KAISOU',"A_CHIZURU: the walkway wall fills the view beside them with the fluorescent tube above it, then the view turns slowly along the wall towards the hall doorway, then settles on the lit doorway, while the shadow of the doorframe lies across the boards",'rouka','pov_look','Q',None,None),
('K11','KAISOU',"A_CHIZURU: the doorway of the walkway frames the hall ahead of the view, then the view holds on the woman in the navy jacket walking away from the camera down the middle of the hall with a blue booklet in her hand, then she grows smaller among the rows of bedding, while the shadows of the roof beams lie across the floor, as families lie still on both sides",'rouka','pov_look','Q',None,None),
('K12','KAISOU',"A_CHIZURU: their own knees fill the bottom of the view on the narrow blue sheet, then their own hand comes down flat on the boards beside them, then takes the weight as the view begins to rise, while the wind blows the rain past the doorway beyond",'rouka','pov_sit','Q',None,None),
]
