# -*- coding: utf-8 -*-
"""Phan C cua S: S5 (18) + S6 (17) + S7 (28) + KET (50) = 113 clip.
Them 2 preset ma doan ket can: `genkan` (cua nha) va `keijiban` (bang tin khu pho)."""

P_EXTRA = {
 "genkan": "the entrance hall of a small Japanese house, a concrete step down to the door, a pair of worn plastic sandals set neatly side by side on the step, a frosted glass sliding door with daylight behind it, a narrow wooden corridor going back into the house",
 "keijiban": "a neighbourhood noticeboard on a residential street in Japan, a shallow glass-fronted case on two posts, a low block wall behind it, bicycles parked along the kerb, plain houses down the street",
}
CROWD_EXTRA = {"genkan": ("solo", "cua nha rieng — vang la dung"), "keijiban": "few"}

SC = []

# ══ S5 22:50–25:15 — 18 clip — camera, DO BA TU DI XIN MO ══
SC += [
('G00','S5',"A_CHIZURU: the walkway runs away ahead of the view towards the school building, then the view carries along it away from the hall left to right across the frame, then stops at a lit doorway at the far end, while the wind blows the rain past the doorway beyond",'rouka','pov_walk','Q','AN',"the view stopped at the lit doorway at the end of the walkway"),
('G01','S5',"A_CHIZURU: the staff room opens out ahead of the view through the doorway, then the rows of desks stand under one lit tube, then a man at the nearest desk looks up towards the camera side, while the shadow of the trolley shifts on the floor",'shokuin','pov_look','Q','AN',None),
('G02','S5',"A_KYOTO sits at a desk in the staff room looking up at someone standing in front of him, filmed over the standing shoulder so his face is towards the frame, then he sets down his pen, then he pushes his chair back and stands, while the shadow of the trolley shifts on the floor",'shokuin','ots','Q',None,None),
('G03','S5',"A_CHIZURU: the staff room fills the view with a laptop and a projector standing on a trolley between the desks, then a hand takes hold of the trolley handle, then pulls it round to face the door, while the shadow of the trolley shifts on the floor",'shokuin','pov_stand','Q',None,None),
('G04','S5',"A_KYOTO pushes the trolley out of the staff room doorway, filmed from behind the whole time, then he turns it into the walkway, then he goes on away from the camera towards the hall, while the shadow of the doorframe lies across the boards",'rouka','behind','Q',None,None),
('G05','S5',"A_CHIZURU: the wall of the gymnasium fills the view in the dark, then a rectangle of white light opens on the wall, then it settles and steadies there, while the shadows of the roof beams lie across the floor, as heads come up from the bedding all across the floor",'taiikukan','pov_look','Q','AP',"the lit rectangle steady on the wall of the hall"),
('G06','S5',"A_CHIZURU: the bright rectangle on the wall fills the view showing a grey overhead picture of the reception table, then two figures in the picture move at the table, then the picture holds still on them, while dust turns in the beam of the projector, as families on the floor sit up to watch",'taiikukan','pov_look','Q','AP',None),
('G07','S5',"A_CHIZURU: the lit rectangle fills the view showing a grey picture of the walkway, then a figure in the picture is shown to the narrow strip of sheet by the door, then the picture holds still on the strip, while dust turns in the beam of the projector, as families on the floor watch without moving",'taiikukan','pov_look','Q',None,None),
('G08','S5',"A_CHIZURU: the lit rectangle fills the view showing the reception table again, then A_MAGO in the picture bows his head once, then twice, while dust turns in the beam of the projector, as the hall behind stays quiet",'taiikukan','pov_look','Q','AQ',"the picture on the wall holding on A_MAGO bowing"),
('G09','S5',"A_CHIZURU: the same picture holds on the wall, then A_MAGO in it bows a third time, then nobody in the picture moves at all, while dust turns in the beam of the projector, as somebody on the floor draws in a breath",'taiikukan','pov_look','Q','AQ',None),
('G10','S5',"A_CHIZURU: the rows of families fill the view sitting up on the sheets with the light off the wall on their faces, then two of them turn to each other, then they turn back to the wall, while the shadow of the roof beams moves across them, as the whole floor keeps watching",'taiikukan','pov_look','Q',None,None),
('G11','S5',"A_CHIZURU: the lit rectangle fills the view showing a figure carrying a folded blanket across the picture, then the blanket is set down at the far side, then the figure comes back the way it went, while dust turns in the beam of the projector, as the hall behind stays quiet",'taiikukan','pov_look','Q',None,None),
('G12','S5',"A_CHIZURU: the same picture holds on the wall, then a figure at the table lifts a microphone in the picture, then holds it up, while dust turns in the beam of the projector, as the floor behind goes completely still",'taiikukan','pov_look','Q',None,None),
('G13','S5',"A_SETSUKO stands alone in front of the lit rectangle on the wall with her back to the camera, then she turns her head away from the picture, then lowers her head, while the shadow of her shoulders moves on the lit wall, as the whole floor of families watches from behind her",'taiikukan','behind','Q','AR',"A_SETSUKO standing with her head lowered in front of the lit wall"),
('G14','S5',"A_SETSUKO stands with her head lowered in front of the lit wall, filmed from high up so her face is not readable, then she moves one step out of the beam, then she stops at the edge of the light, while the shadow of her shoulders moves on the lit wall, as the families on the floor watch from all round",'taiikukan','high','Q','AR',None),
('G15','S5',"A_CHIZURU: the beam of the projector fills the view across the dark hall, then the picture on the wall goes out, then the ordinary ceiling lights come up again, while dust turns in the beam of the projector, as the floor sits up blinking in the light",'taiikukan','pov_look','Q',None,None),
('G16','S5',"A_KYOTO stands at the trolley beside the wall and closes the laptop, filmed over his shoulder, then he unplugs the lead, then he coils it round his hand, while the shadows of the roof beams lie across the floor, as families on the sheets watch him from behind",'taiikukan','ots','Q',None,None),
('G17','S5',"A_CHIZURU: the hall fills the view with everyone sitting up on the sheets, then they turn their heads together towards the middle of the floor, then they stay turned that way, while the shadows of the roof beams lie across the floor, as nobody lies back down",'taiikukan','pov_look','Q',None,None),
]

# ══ S6 25:15–27:30 — 17 clip — thu nhan cong khai ══
SC += [
('H20','S6',"A_SETSUKO walks from the wall into the middle of the hall, filmed from behind the whole time, then she comes on down the aisle between the rows, then she stops in the open middle of the floor, while the shadows of the roof beams lie across the floor, as families draw back on both sides to let her through",'taiikukan','behind','Q','AS',"A_SETSUKO standing in the open middle of the floor"),
('H21','S6',"A_CHIZURU: the woman in the navy jacket stands a few paces away in the middle of the hall, filmed past their own shoulder, then she moves one step closer, then stops and stands still, while the shadows of the roof beams lie across the floor, as families on the sheets all round stay sitting up",'taiikukan','pov_stand','Q','AS',None),
('H22','S6',"A_SETSUKO stands a few paces off with her hands down at her sides, filmed over the shoulder of the person facing her, then she lifts one hand as if to speak, then lets it fall again, while the shadows of the roof beams lie across the floor, as the floor round them stays silent",'taiikukan','ots','Q',None,None),
('H23','S6',"A_CHIZURU: the rows of families fill the view sitting up on the blue sheets, then the view turns slowly along the whole floor from one side to the other, then stops facing back down the hall, while the shadow of the roof beams moves across them, as every one of them stays turned the same way",'taiikukan','pov_look','Q',None,None),
('H24','S6',"A_CHIZURU: the far wall of the hall fills the view across the heads of the crowd, then the view holds on the place along that wall, then stays there without moving, while the shadows of the roof beams lie across the floor, as the whole floor stays turned this way",'taiikukan','pov_look','Q',None,None),
('H25','S6',"A_SETSUKO stands in the middle of the floor listening, filmed from high up so her face is not readable, then her shoulders come down, then her hands come together in front of her, while the shadows of the roof beams lie across the floor, as the families on the floor watch from all round",'taiikukan','high','Q',None,None),
('H26','S6',"A_CHIZURU: the nearest row of families fills the bottom of the view, then an older man in it lowers his head, then he keeps it down, while the shadows of the roof beams lie across the floor, as the people beside him stay quite still",'taiikukan','pov_look','Q',None,None),
('H27','S6',"A_CHIZURU: the far corner of the hall fills the view with the old man sitting against the wall, then he turns his head towards the camera side, then lowers it in a small nod, while the shadow of the blanket lies still across his knees, as the people near him look the same way",'sumi','pov_look','Q',None,None),
('H28','S6',"A_ICHINOSE sits against the wall with the blanket over his knees, filmed over the shoulder of A_MAGO so his face is turned away, then he lifts one hand off the blanket towards the middle of the hall, then lets it settle back, while the shadow of his shoulders lies still on the wall",'sumi','ots','Q',None,None),
('H29','S6',"A_CHIZURU: A_SHONIN sits on a sheet halfway along the hall, then she gets to her feet where she is, then she stands there facing the middle of the floor, while the shadows of the roof beams lie across the floor, as the people around her look up at her",'taiikukan','pov_look','Q','AT',"A_SHONIN standing up alone among the seated rows"),
('H30','S6',"A_SHONIN walks from her place across the aisle towards the far corner, filmed from behind the whole time, then she reaches the corner, then she sits down on the sheet beside the old man, while the shadows of the roof beams lie across the floor, as the rows she passes turn to watch her go",'taiikukan','behind','Q','AT',None),
('H31','S6',"A_CHIZURU: the rows of bedding fill the view across the hall, then two more families take up their bags, then they move them along the floor away from the middle, while the shadows of the roof beams lie across the floor, as others down the row begin to do the same",'taiikukan','pov_look','Q',None,None),
('H32','S6',"the floor of the hall from high up under the roof, then people begin shifting their places across it one after another, then the middle of the floor is left wide and empty, while the shadows of the roof beams lie across the floor, as the movement runs to the far end",'taiikukan','high','Q',None,None),
('H33','S6',"A_SETSUKO stands alone in the wide empty middle of the floor, filmed from behind the whole time, then she turns slowly all the way round, then she stops facing the far corner, while the shadows of the roof beams lie across the floor, as the families sit on their sheets at every side of her",'taiikukan','behind','Q',None,None),
('H34','S6',"A_CHIZURU: the empty middle of the floor fills the view with the one figure standing in it, then nobody comes near her, then the rows on both sides stay where they are, while the shadows of the roof beams lie across the floor, as the whole floor keeps its distance",'taiikukan','pov_look','Q',None,None),
('H35','S6',"A_CHIZURU: the high windows fill the top of the view with the rain gone off them, then the first grey light shows through the glass, then the view comes down to the floor again, while the shadow from the high windows shifts a little, as the floor sits quiet below",'taiikukan','pov_look','Q',None,None),
('H36','S6',"A_CHIZURU: their own hand comes to rest on the flap of the cloth shoulder bag in the bottom of the view, then the fingers close on the corner of it, then hold there without lifting it, while the shadows of the roof beams lie across the floor",'taiikukan','pov_hand','Q',None,None),
]

# ══ S7 27:30–31:10 — 28 clip — cua mo, nham nguoi ══
SC += [
('J00','S7',"the two front doors of the gymnasium in the early morning stand shut with light behind them, then both doors swing open together, then the low morning sun comes straight in across the wooden floor, while dust turns in the light, as the people on the floor all turn towards the doors",'asa','wide','Q','AU',"both doors standing open with the morning sun coming in across the floor"),
('J01','S7',"A_CHIZURU: the open doors fill the far end of the view with the morning sun behind them, then figures in dark suits come in against the light, then they start down the hall towards the camera side, while dust turns in the light from the doors, as families sitting up on the sheets turn to watch",'asa','pov_look','Q','AU',None),
('J02','S7',"A_CHIZURU: the group in dark suits comes on down the hall towards the view, then they keep coming without stopping, then they pass the first rows of bedding, while dust turns in the light from the doors, as families on both sides draw their bedding in as they pass",'asa','pov_look','Q',None,None),
('J03','S7',"A_SETSUKO hurries out into the middle of the aisle ahead of the oncoming group, filmed from behind the whole time, then she stops in their path, then she smooths her jacket down with both hands, while dust turns in the light from the doors, as the families on the floor watch from all round",'asa','behind','Q','AV',"A_SETSUKO standing in the aisle in the path of the group"),
('J04','S7',"A_SETSUKO stands in the aisle with her hands folded in front of her and bows deeply towards the oncoming figures, filmed from behind the whole time, then she stays bent over as they walk past on either side of her, then she straightens slowly into the empty aisle, while dust turns in the light from the doors, as the families on the floor watch from all round",'asa','behind','Q','AV',None),
('J05','S7',"A_CHIZURU: the group in dark suits fills the view coming on down the aisle, then they pass the bowing figure without slowing, then they come on towards the camera side, while dust turns in the light from the doors, as heads turn to follow them along the rows",'asa','pov_look','Q',None,None),
('J06','S7',"A_SETSUKO straightens up in the empty aisle and turns to look after the group, filmed from high up so her face is not readable, then she moves one step after them, then she stops where she is, while dust turns in the morning sun across the boards, as the families on the floor watch from all round",'asa','high','Q',None,None),
('J07','S7',"A_CHIZURU: A_SHITSUCHO comes to a stop directly ahead of the view, then he straightens his jacket, then he bows his head towards the camera side and holds it there, while dust turns in the morning light past him, as the whole hall behind him goes still",'asa','pov_look','Q','AW',"the man in the dark suit with his head bowed towards the view"),
('J08','S7',"A_CHIZURU: the same man holds his bow ahead of the view, then he straightens, then the men behind him bow their heads in turn, while dust turns in the morning light past him, as the hall behind them stays silent",'asa','pov_look','Q','AW',None),
('J09','S7',"A_SETSUKO stands in the aisle looking towards the group and the person they are bowing to, filmed from behind the whole time, then her hands come apart at her sides, then they fall and hang there, while dust turns in the morning sun across the boards, as the floor all round stays turned that way",'asa','behind','Q',None,None),
('J10','S7',"A_CHIZURU: their own hand comes into the bottom of the view and opens the flap of the cloth shoulder bag, then it draws out a single folded sheet of plain paper, then holds it steady at the edge of the frame, while dust turns in the morning sun across the boards",'asa','pov_hand','Q','AX',"their own hand holding the folded sheet of paper clear of the bag"),
('J11','S7',"A_CHIZURU: their own hand holds the folded sheet of plain paper in the bottom of the view, then it lays the paper flat on the reception table, then withdraws and leaves it lying there, while dust turns in the morning sun across the table",'uketsuke','pov_hand','Q','AX',None),
('J12','S7',"A_SHITSUCHO stands at the reception table looking down at a single sheet of paper lying on it, filmed over his shoulder, then he picks it up, then he holds it out to the man beside him, while dust turns in the morning sun across the table, as evacuees behind them look on",'uketsuke','ots','Q',None,None),
('J13','S7',"A_SETSUKO comes up to the reception table and looks down at the sheet of paper on it, filmed from behind the whole time, then she leans in over it, then she stands back up straight, while dust turns in the morning sun across the table, as the men in suits stand back from the table",'uketsuke','behind','Q',None,None),
('J14','S7',"A_CHIZURU: the woman in the navy jacket stands at the table with her arms at her sides, then the blue booklet slips out from under her arm, then it falls to the boards at her feet, while dust turns in the morning sun across the table, as the men in suits look down at it",'uketsuke','pov_look','Q',None,None),
('J15','S7',"the varnished floor of the hall fills the view in the morning sun with a thin blue booklet lying open on it, then the top page lifts and turns over in the draught from the doors, then settles flat again, while dust turns in the light",'asa','still','Q','AY',"the blue booklet lying open on the floor with its pages settled"),
('J16','S7',"the same booklet lies open on the boards in the morning sun, then the draught turns one more page, then it stops on the last leaf, while dust turns in the light",'asa','still','Q','AY',None),
('J17','S7',"the last page of the open booklet fills the frame on the sunlit boards, then the light moves slowly across it, then it reaches the bottom of the page, while dust turns in the light",'asa','still','Q',None,None),
('J18','S7',"A_SETSUKO, filmed from high up so her face is not readable, goes down onto her knees on the wooden floor beside the open booklet, then she stays there with her head down, then her shoulders drop, while dust turns in the morning sun across the boards, as the families on the floor watch from all round her",'asa','high','Q',None,None),
('J19','S7',"A_SETSUKO kneels on the boards beside the booklet, filmed from behind the whole time, then she reaches out towards it, then she draws the hand back without touching it, while dust turns in the morning sun across the boards, as nobody on the floor comes near her",'asa','behind','Q',None,None),
('J20','S7',"A_CHIZURU: the kneeling figure fills the middle of the view on the sunlit boards, then the men in dark suits stand back from her, then nobody moves towards her, while dust turns in the morning sun across the boards, as the whole hall stays where it is",'asa','pov_look','Q',None,None),
('J21','S7',"A_CHIZURU: their own hand comes into the bottom of the view and picks the blue booklet up off the boards, then it brushes the dust off the cover, then holds it closed at the edge of the frame, while dust turns in the morning sun across the boards",'asa','pov_hand','Q',None,None),
('J22','S7',"A_CHIZURU: the far corner of the hall fills the view in the morning light with the old man awake against the wall, then he lifts his head towards the camera side, then he holds it there, while dust turns in the morning sun across the boards, as A_MAGO sits up beside him",'sumi','pov_look','Q',None,None),
('J23','S7',"A_CHIZURU: the rows of families fill the view in the morning light folding their bedding, then they turn their heads together towards the middle of the hall, then they go back to folding, while dust turns in the morning sun across the boards, as the floor slowly empties",'asa','pov_look','Q',None,None),
('J24','S7',"A_CHIZURU: the open doors fill the far end of the view with the morning sun coming in, then people begin carrying bags out through them away from the camera, then the doorway fills with the light behind them, while dust turns in the light from the doors, as more families rise along the rows",'asa','pov_look','Q',None,None),
('J25','S7',"the hall from high up under the roof in the morning, then the blue sheets are pulled up one after another across the floor, then the bare boards show through in patches, while dust turns in the morning sun across the boards, as families carry their bedding away down the aisles",'asa','high','Q',None,None),
('J26','S7',"A_SETSUKO is helped up off the boards by A_SHITSUCHO, filmed from behind the whole time, then she stands with her head down, then she is led away towards the doors, while dust turns in the morning sun across the boards, as the families still on the floor watch her go",'asa','behind','Q',None,None),
('J27','S7',"A_CHIZURU: the empty middle of the floor fills the view in the morning sun, then the last of the blue sheet is folded away from it, then the bare boards are left shining, while dust turns in the light, as people carry bedding past on both sides",'asa','pov_look','Q',None,None),
]

# ══ KET 31:10–37:50 — 50 clip ══
SC += [
# hau qua
('L00','KET',"the wet apron outside the gymnasium in daylight with the storm gone, then the standing water runs away down the slope, then the last of it drains off the concrete, while the wind moves the puddles",'soto','still','Q',None,None),
('L01','KET',"the two front doors of the gymnasium stand open on a bright still day with nobody in them, then the light lies flat across the bare boards inside, then a draught moves the dust in it, while dust turns in the light",'asa','still','Q',None,None),
('L02','KET',"a small city car pulls up on the apron outside the gymnasium and two figures get out of it, then they cross the concrete towards the doors away from the camera, then they go in through them, while the wind moves the puddles, as a caretaker holds the door for them",'soto','wide','Q',None,None),
('L03','KET',"two figures in plain jackets stand at the bare reception table with files open on it, filmed over one shoulder, then one of them turns a page away from the camera, then the other writes something down, while dust turns in the daylight across the table, as the empty hall stands quiet behind them",'uketsuke','ots','Q',None,None),
('L04','KET',"A_CHIZURU: the bare reception table fills the bottom of the view with two open files on it, then a hand lays a third file down beside them, then squares the edges of all three towards the camera, while dust turns in the daylight across the table",'uketsuke','pov_hand','Q',None,None),
('L05','KET',"the neighbourhood noticeboard stands on the street in the morning with a fresh sheet pinned inside the glass, then the sheet lifts a little at one corner, then settles flat against the board, while the wind moves the bicycles along the kerb",'keijiban','still','Q','BA',"the fresh sheet pinned flat inside the noticeboard glass"),
('L06','KET',"two neighbours stand at the noticeboard reading the sheet behind the glass, filmed over their shoulders so their faces are turned away, then one of them points at the bottom of it, then they both step back from the board, while the wind moves the bicycles along the kerb, as another passer-by slows to look",'keijiban','ots','Q','BA',None),
('L07','KET',"the noticeboard stands empty of readers on the quiet street, then the sheet behind the glass lifts at the corner again, then it settles, while the wind moves the bicycles along the kerb",'keijiban','still','Q',None,None),
('L08','KET',"a hand in a plain sleeve opens the glass front of the noticeboard and takes down an old sheet, filmed over the shoulder, then folds it in half, then closes the glass front again, while the wind moves the bicycles along the kerb, as a neighbour passes behind on the pavement",'keijiban','ots','Q',None,None),
('L09','KET',"the street outside the noticeboard in the middle of the day, then a woman with a shopping bag walks down it away from the camera, then she turns in at a gate without looking at the board, while the wind moves the bicycles along the kerb, as two other people pass the other way",'keijiban','wide','Q',None,None),
# mua dong — sieu thi
('L10','KET',"the car park of the supermarket on a grey winter afternoon, then the wind moves the line of trolleys a little, then a plastic bag goes across the concrete left to right across the frame, while the wind moves the awnings, as shoppers cross the car park in the distance",'supa','wide','Q',None,None),
('L11','KET',"A_CHIZURU: the supermarket car park fills the view on a grey winter afternoon, then a woman in a plain coat with a shopping basket stops a few paces ahead and bows deeply towards the camera side, then straightens and stands still, while the wind moves the awnings behind her, as other shoppers cross the car park behind her",'supa','pov_look','Q','BB',"the woman with the basket standing still after bowing"),
('L12','KET',"A_CHIZURU: the woman with the basket stands a few paces ahead of the view, then their own head lowers so the view dips towards the concrete, then it comes back up to her, while the wind moves the awnings behind her, as shoppers pass on both sides of her",'supa','pov_look','Q','BB',None),
('L13','KET',"a woman in a plain coat stands still in the car park holding a shopping basket, filmed from behind the whole time, then she turns away towards the shopfront, then she walks off across the concrete away from the camera, while the wind moves the awnings, as other shoppers pass her going the other way",'supa','behind','Q',None,None),
('L14','KET',"A_CHIZURU: the car park stretches away ahead of the view, then the view turns back over their own shoulder towards the shopfront, then holds on the woman with the basket standing alone among the parked cars, while the wind moves the awnings, as shoppers pass on both sides of her",'supa','pov_look','Q',None,None),
('L15','KET',"the line of trolleys stands against the wall of the supermarket with nobody at them, then one trolley rolls a hand's width in the wind, then it comes up against the next and stops, while the wind moves the awnings",'supa','still','Q',None,None),
# cu ong qua mua dong
('L16','KET',"A_CHIZURU: the entrance hall of a small house fills the view with a pair of worn plastic sandals on the step, then the light from the frosted door moves across them, then it reaches the edge of the step, while dust turns in the light from the doorway",'genkan','pov_look','Q',None,None),
('L17','KET',"A_CHIZURU: the pair of worn sandals fills the bottom of the view on the concrete step, then their own hand comes down and squares them side by side, then withdraws and leaves them set straight, while dust turns in the light from the doorway",'genkan','pov_hand','Q',None,None),
('L18','KET',"the frosted glass door of the house entrance with winter daylight behind it, then a shadow passes on the far side of the glass, then the light comes back even again, while dust turns in the light from the doorway",'genkan','still','Q',None,None),
('L19','KET',"A_CHIZURU: the narrow corridor of the house runs away ahead of the view from the step, then the view carries along it away from the camera, then stops where a low table stands at the end, while dust turns in the light from the doorway",'genkan','pov_walk','Q',None,None),
('L20','KET',"A_CHIZURU: the low table at the end of the corridor fills the bottom of the view with a thin blue booklet lying on it, then their own hand opens the booklet at the last page, then holds it open there, while dust turns in the light from the doorway",'genkan','pov_hand','Q','BC',"the booklet lying open at its last page on the low table"),
('L21','KET',"A_CHIZURU: the open last page fills the bottom of the view on the table, then their own hand lays a pen down across it, then draws back from the table, while dust turns in the light from the doorway",'genkan','pov_hand','Q','BC',None),
('L22','KET',"A_CHIZURU: the open page fills the bottom of the view with the pen lying on it, then their own hand takes the pen up again, then writes one short line at the foot of the page, while dust turns in the light from the doorway",'genkan','pov_hand','Q',None,None),
('L23','KET',"A_CHIZURU: the table fills the view with the closed booklet and the pen beside it, then their own hand rests flat on the cover, then lifts away and leaves it shut, while dust turns in the light from the doorway",'genkan','pov_hand','Q',None,None),
# mua xuan — dien tap
('L24','KET',"the gymnasium in spring with the doors open on a green schoolyard, trestle tables set out across the boards, then the light lies flat over the empty tables, then a draught from the doors moves a paper on one of them, while dust turns in the daylight across the boards",'haru','wide','Q',None,None),
('L25','KET',"A_CHIZURU: the spring gymnasium opens out ahead of the view from the doorway, then the view carries in along the line of trestle tables left to right across the frame, then stops at the first table, while dust turns in the daylight across the boards, as helpers set out boxes along the row",'haru','pov_walk','Q','BD',"the view stopped at the first trestle table"),
('L26','KET',"A_CHIZURU: a trestle table fills the bottom of the view with a cardboard box of sharpened pencils standing on it, then their own hand turns the box a little towards the room, then withdraws and leaves it standing open, while dust turns in the daylight from the open doors",'haru','pov_hand','Q','BD',None),
('L27','KET',"A_CHIZURU: the box of pencils fills the bottom of the view, then their own hand lifts one pencil out of it, then stands it back among the others, while dust turns in the daylight across the boards",'haru','pov_hand','Q',None,None),
('L28','KET',"A_CHIZURU: the spring gymnasium opens out ahead of the view with the tables set out for a drill, then a queue of local people comes in through the open doors towards the tables, then the first of them reaches the table, while dust turns in the daylight across the boards, as more people come in behind them",'haru','pov_look','Q',None,None),
('L29','KET',"a queue of local people waits at the trestle table in the spring gymnasium, filmed over the shoulder of the person at the front, then the one at the front takes something off the table, then steps aside for the next, while dust turns in the daylight across the boards, as the queue moves up behind them",'haru','ots','Q',None,None),
('L30','KET',"A_CHIZURU: the table fills the bottom of the view with an open ledger on it, then a hand from the queue side writes a name into the ruled column, then lifts the pencil away from the page, while dust turns in the daylight across the boards",'haru','pov_hand','Q','BE',"a name written into the ruled column of the open ledger"),
('L31','KET',"A_CHIZURU: the ruled column fills the bottom of the view with a run of names down it, then another name is added at the foot of the run away from the camera, then the pencil is set back in the box, while dust turns in the daylight across the boards",'haru','pov_hand','Q','BE',None),
('L32','KET',"A_CHIZURU: the queue at the table fills the view, then a woman near the front holds a pencil up and says something, then the people around her look at it too, while dust turns in the daylight across the boards, as the queue keeps moving up",'haru','pov_look','Q',None,None),
('L33','KET',"a woman in the queue holds a pencil up in front of her, filmed over her shoulder so her face is turned away, then she turns it over in her fingers, then she bends to the ledger with it, while dust turns in the daylight across the boards, as the next in the queue waits behind her",'haru','ots','Q',None,None),
('L34','KET',"A_CHIZURU: the length of the spring gymnasium fills the view with the drill going on down it, then the view turns slowly right to left across the frame along the tables, then stops on the open doors and the green yard beyond, while dust turns in the daylight across the boards, as helpers work at every table",'haru','pov_look','Q',None,None),
('L35','KET',"the open doors of the spring gymnasium from inside with the green schoolyard beyond them, then two figures cross the yard outside left to right across the frame, then they are gone past the doorway, while dust turns in the daylight across the boards",'haru','still','Q',None,None),
('L36','KET',"A_CHIZURU: the wall behind the reception table fills the view with a thin blue booklet hanging open on a cord, then the pages lift a little in the draught from the doors, then settle back against the wall, while dust turns in the daylight across the boards",'haru','pov_look','Q','BF',"the blue booklet hanging open on its cord against the wall"),
('L37','KET',"A_CHIZURU: the hanging booklet fills the bottom of the view against the wall, then their own hand turns it to the last page, then lets it hang straight again, while dust turns in the daylight across the boards",'haru','pov_hand','Q','BF',None),
('L38','KET',"the thin blue booklet hangs open on its cord against the wall of the spring gymnasium, then a draught from the doors turns one page, then it settles back, while dust turns in the daylight across the boards",'haru','still','Q',None,None),
('L39','KET',"an older man stops at the wall and reads the hanging booklet, filmed over his shoulder so his face is turned away, then he turns a page of it, then he lets it fall back and moves away, while dust turns in the daylight across the boards, as other people pass behind him",'haru','ots','Q',None,None),
('L40','KET',"A_CHIZURU: the spring gymnasium fills the view with the drill going on, then a helper at the far table lifts a folded blanket out of a box, then holds it up to show the queue, while dust turns in the daylight across the boards, as the people at that table gather round",'haru','pov_look','Q',None,None),
('L41','KET',"A_CHIZURU: a corner of the spring gymnasium fills the view where the store door stands open, then the equipment store is shown lit inside, then a distribution board is left standing open beside it, while dust turns in the daylight across the boards",'haru','pov_look','Q',None,None),
('L42','KET',"the open store door of the spring gymnasium with the padlock hanging unlocked on its hasp, then the draught moves the open door a little, then the padlock swings and stops, while dust turns in the daylight across the boards",'haru','still','Q',None,None),
('L43','KET',"A_CHIZURU: the plug socket low on the wall of the hall fills the bottom of the view with nothing in it, then their own hand rests flat on the wall beside it, then comes away again, while dust turns in the daylight across the boards",'haru','pov_hand','Q',None,None),
('L44','KET',"A_CHIZURU: the spring gymnasium opens out ahead of the view with the drill winding up, then the queues thin out along the tables, then the last people go out through the open doors, while dust turns in the daylight across the boards, as helpers begin folding the tables down",'haru','pov_look','Q',None,None),
('L45','KET',"the trestle tables of the spring gymnasium stand cleared at the end of the drill, then the light from the doors moves along the bare table tops, then it reaches the box of pencils at the end, while dust turns in the daylight across the boards",'haru','still','Q',None,None),
('L46','KET',"A_CHIZURU: the box of pencils stands on the cleared table in the bottom of the view, then their own hand closes the flaps of the box over them, then leaves it standing shut, while dust turns in the daylight across the boards",'haru','pov_hand','Q',None,None),
('L47','KET',"A_CHIZURU: the entrance hall of the house fills the view again with the worn sandals on the step, then the evening light comes through the frosted door onto them, then it moves off them as the light goes, while dust turns in the light from the doorway",'genkan','pov_look','Q',None,None),
('L48','KET',"the pair of worn plastic sandals stands squared on the concrete step of the house entrance, then the last of the daylight goes off the frosted glass behind them, then the step is left in even shade, while dust turns in the light from the doorway",'genkan','still','Q',None,None),
('L49','KET',"the empty spring gymnasium with the doors open on the green yard, the tables folded and stacked along one wall, then the draught moves the hanging booklet on its cord, then it settles against the wall, while dust turns in the daylight across the boards",'haru','still','Q',None,None),
]
