# -*- coding: utf-8 -*-
"""_collage_full23.py — 78 cảnh còn lại của video 23, viết theo CÔNG THỨC ĐÃ DUYỆT ở LOT1.

Công thức (user duyệt 2026-09-12 sau 3 vòng sửa):
  ① NGƯỜI cắt từ giấy ảnh — nhân vật thật, không phải sơ đồ trừu tượng
  ② CON SỐ to cắt từ giấy màu — ⚖️ chỉ số CÓ THẬT trong lời đọc của chính cảnh đó
  ③ BIỂU ĐỒ / quan hệ vật — cột, kim, dải lịch, cân, bậc thang
  ④ CHUYỂN ĐỘNG viết TAY bám đúng vật trong khung (kho chung mù với cảnh viết tay)

🔴 Vì sao phải viết tay từng cảnh: vòng 1 dùng kho chung xoay theo khuôn ⇒ cảnh "bà + sổ +
   số 0" nhận phải câu "các mảnh xếp chồng bắn lên như biểu đồ cột". Đó là bệnh
   khối-chung-chọi-mô-tả, đã dính 7 lần trong dự án này.
"""

# scene_index -> mô tả cảnh (đi vào `_scenes23.SCENES`)
SCENES_V3 = {
2:   'VIZ: an elderly woman cut from photographic paper stands at the right, and filling the left two thirds a huge numeral 1,560,000 cut from mustard card is pasted flat, with four torn calendar sheets stacked beneath it',
3:   'VIZ: an elderly man cut from photographic paper watches a long paper strip of identical coins running across the frame, a pair of card scissors open over it two coins from the end, and a big numeral 5 cut from deep red card above the blade',
4:   'an elderly man cut from grainy photographic paper with his brow strip pulled together, an empty torn-paper speech bubble taped beside his head and a question-mark-shaped paper accent behind him',
9:   'META: an elderly woman cut from photographic paper watches a channel of cut-out coins flowing left to right, a single postcard dropping into a slot above it and a plain paper gate swinging down to block the channel, a numeral 1 cut from red card beside the postcard',
13:  'HOLD: an elderly man cut from photographic paper holds an opened paper form square-on, its five ruled boxes each already filled with a solid bar of charcoal ink, a taped arrow pointing at the filled boxes',
14:  'VIZ: an elderly woman cut from photographic paper stands beside a tall paper filing cabinet with its drawer pulled open, packed edge to edge with identical blank record cards spilling toward her',
16:  'SPLIT: an elderly man cut from photographic paper stands between a paper envelope on its doorstep and an empty cut-out money box, the bridge of paper between them severed in the middle, a numeral 0 cut from red card in the gap',
17:  'an elderly woman cut from photographic paper leaning forward with one paper hand raised, a row of small cut-out envelopes fanned behind her shoulder',
18:  'CROWD: a street of flat paper houses seen head-on with elderly cut-out figures on the doorsteps, envelopes landing on most of the steps and four houses left with nothing on theirs',
19:  'DESK: an elderly woman cut from photographic paper at a paper desk, a calculator cut from grey card in front of her and a blank paper bar chart of three empty outlined bars pinned behind her',
21:  'VIZ: an elderly man cut from photographic paper stands between two heavy law volumes cut from dark card, big numerals 102 and 92 cut from cream card pasted on their open pages',
22:  'META: an elderly woman cut from photographic paper watches two tall paper hourglasses standing side by side, sand running in both, a numeral 5 cut from charcoal card between them',
23:  'META: twelve small solid paper blocks stand in a row with an elderly man cut from photographic paper at the end of the row, the leftmost block sinking away below the surface, a numeral 12 cut from card above the row',
24:  'VIZ: forty-eight tiny paper coins laid in four rows of twelve with an elderly woman cut from photographic paper leaning over them, a big numeral 48 cut from mustard card at the side',
26:  'VIZ: one paper coin cut large in the foreground carrying a numeral 32,000 cut from charcoal card, the full grid of forty-eight small coins running away behind it, an elderly man cut-out at the edge',
27:  'VIZ: a row of cut-out coins riding a paper conveyor strip with the leading coin tipping into a torn dark gap, an elderly woman cut from photographic paper watching, a numeral 32,000 cut from red card above the gap',
28:  'DESK: an elderly man cut from photographic paper at a paper desk with a calculator and an open blank notebook, an empty torn-paper thought bubble above his head',
30:  'VIZ: one envelope at the top with four torn paper paths running down from it to four cut-out boxes, an elderly woman cut from photographic paper at the side, a big numeral 4 cut from charcoal card beside the branch point',
31:  'SPLIT: an elderly man cut from photographic paper between a thick cream envelope on the left and a single thin postcard on the right, a numeral 10 cut from red card above the postcard',
33:  'VIZ: an elderly woman cut from photographic paper holding the thin postcard up large in the foreground while the thick envelope sits small and dull behind her, a taped arrow swinging from the envelope to the postcard',
35:  'VIZ: a horizontal bar of stacked paper squares with several squares missing and an elderly man cut from photographic paper laying a fresh square into a gap, a numeral 60 cut from mustard card above the bar',
36:  'an elderly man cut from photographic paper with his chin lifted and chest strip rising, a paper bar chart behind him whose last bar has just closed the gap to the dashed tape line',
37:  'HOLD: an elderly woman cut from photographic paper holding a blank application sheet out flat toward the camera, a taped arrow curving from her hand toward a cut-out counter behind her',
39:  'VIZ: an elderly man cut from photographic paper beside a long paper bar with a clean scissor cut a third of the way along, the severed longer piece lying discarded, numerals 25 and 10 cut from card at the two ends',
41:  'VIZ: a paper timeline strip with two torn notches, a postcard landing on each, an elderly woman cut from photographic paper behind it, numerals 60 and 65 cut from charcoal card above the two notches',
42:  'an elderly woman cut from photographic paper with her chin lowered, a thin postcard slipping off the edge of the paper table in front of her',
43:  'VIZ: a paper balance scale, the pan with a single thin postcard hanging low and the pan with a thick envelope riding high, an elderly man cut from photographic paper watching the tilt',
44:  'VIZ: two different paper letterheads pinned side by side as plain colour blocks with an elderly woman cut from photographic paper between them, a taped arrow running out from the second one',
45:  'CROWD: the sorting floor of a post office in flat paper panels, three staff cut-outs at a long counter stacked with trays of envelopes, one envelope flying out of frame',
46:  'VIZ: an envelope bouncing off the door of a paper house and flying back, an elderly man cut from photographic paper standing at a second house further along with an empty step',
47:  'CROWD: a ward office counter in paper panels, a clerk cut-out and an elderly visitor cut-out facing each other, a stack of forms between them and seated figures waiting behind',
48:  'an elderly man cut from photographic paper turning his head, a paper envelope on a taped arrow curving away from one house toward another behind him, a numeral 1 cut from card on the arrow',
50:  'VIZ: a cut-out envelope flying over a torn paper sea toward a distant paper coastline along a dotted masking-tape line, an elderly woman cut from photographic paper small at the near shore',
51:  'VIZ: four envelopes laid in a row each on a different flat colour block, an elderly man cut from photographic paper looking along the row, a big numeral 4 cut from mustard card above them',
52:  'DESK: an elderly woman cut from photographic paper at a paper desk with a teacup and a small stack of documents, a numeral 3 cut from charcoal card pinned on the flat wall behind',
53:  'META: an elderly man cut from photographic paper watching an envelope vanish into a one-way slot in a flat paper wall, the slot sealed with tape behind it and a second envelope stopped in front',
55:  'an elderly man cut from photographic paper with both paper palms lifted, three blank cut-out paths fanning out behind his shoulders',
57:  'VIZ: an elderly woman cut from photographic paper beside a flat paper screen rectangle with a blank document sliding out of its lower edge, a numeral 101 cut from red card on the document',
58:  'VIZ: an elderly man cut from photographic paper holding a paper telephone handset, its cord unrolling across the frame and ending at a small envelope',
59:  'CROWD: a pension office counter in paper panels with a queue of elderly cut-out figures, rows of paper chairs behind them and a clerk cut-out at the window',
61:  'an elderly couple cut from photographic paper seated side by side, both dipping their head strips toward the camera, paper accent shapes fanning out behind them',
62:  'DESK: an elderly man cut from photographic paper at a paper desk with an open blank notebook and a pencil cut from mustard card, a small stack of torn calendar sheets beside it',
63:  'an elderly woman cut from grainy black-and-white photographic paper seated square-on with a teacup cut-out beside her, numerals 66 and 61 cut from charcoal card pinned on the flat wall behind',
64:  'VIZ: four calendar sheets peeling off one after another with an unopened envelope lying face-down beneath them, an elderly woman cut from photographic paper behind, a numeral 4 cut from mustard card above',
66:  'an elderly woman cut from photographic paper with her eyelids lowered and shoulder strips settling, a paper envelope lying unopened on the table edge in front of her',
67:  'META: a large paper clock face with a bare dial and one plain strip for a hand, a small elderly cut-out figure standing directly beneath it on a flat colour field',
68:  'SPLIT: the same paper calendar strip shown twice one above the other, the upper one whole and the lower one with its final two squares torn off, an elderly man cut-out between them, a numeral 2 cut from red card',
69:  'VIZ: a banded stack of paper notes with its top third torn clean away and lying separate, an elderly woman cut from photographic paper reaching toward the separated part',
70:  'an elderly man cut from photographic paper with his head tilted and mouth cut-out open, a taped question-mark accent shape behind his shoulder',
71:  'VIZ: two paper pension slips side by side with an elderly woman cut from photographic paper between them, the right-hand slip crossed out with a strip of dark tape',
74:  'VIZ: a stair of paper blocks rising step by step to the right with an elderly man cut from photographic paper climbing alongside it, a numeral 65 cut from mustard card at the first step',
76:  'an elderly woman cut from photographic paper with her eye cut-outs wide and mouth open, two small paper bar charts pinned behind her, one rising and one flat',
78:  'HOLD: an elderly man cut from photographic paper holding a blank written statement sheet out flat, a taped arrow curving from the sheet toward a cut-out counter behind him',
79:  'VIZ: a paper ledger with one line lifted clean out and replaced by a brighter strip, an elderly woman cut from photographic paper beside it and a full untouched stack of paper notes',
80:  'CROWD: a consultation room in flat paper panels with three desks in a row, a clerk cut-out and an elderly visitor cut-out at each, forms stacked between them',
81:  'HOLD: an elderly woman cut from photographic paper holding a single plain postcard up square-on, a numeral 1 cut from red card pasted beside it',
82:  'VIZ: a paper month grid of blank squares with a postcard landing on the very first square, an elderly man cut from photographic paper at the side of the grid',
84:  'an elderly man cut from photographic paper with both paper hands raised to the sides of his head, a paper money channel behind him with a gate half lowered across it',
86:  'META: a paper channel of cut-out coins with a plain gate lowered across it, the coins piling motionless behind and the channel beyond empty, an elderly woman cut-out watching from the edge',
87:  'VIZ: an elderly man cut from photographic paper staring at a paper bank passbook whose latest entry line is a bare torn gap, a taped arrow pointing into the gap',
89:  'VIZ: two paper slips set apart from a larger pile, each marked with a taped circle, an elderly woman cut from photographic paper lifting one of them, a numeral 1 cut from card above',
90:  'HOLD: an elderly woman cut from photographic paper holding a plain postcard flat, one bare square box on its face marked with a torn paper tick',
91:  'DESK: an elderly man cut from photographic paper at a paper desk with a stack of plain documents, a teacup and an envelope, a paper checklist of blank boxes pinned behind him',
93:  'an elderly woman cut from photographic paper with her head tilted and brow strip drawn together, two adjacent paper calendar squares floating beside her head',
94:  'VIZ: two adjacent squares of a paper calendar grid cut large, the earlier one ringed with torn red paper and the later left bare, an elderly man cut from photographic paper pointing at the ringed one',
98:  'VIZ: two paper certificates side by side, the left yellowed with a torn corner and pushed aside, the right crisp and square, an elderly woman cut-out choosing between them, a numeral 6 cut from charcoal card above the fresh one',
99:  'VIZ: a small cut-out envelope crawling along a long paper calendar strip still far from the marked square at its end, an elderly man cut from photographic paper watching from the near end',
100: 'HOLD: an elderly man cut from photographic paper holding a single plain certificate sheet up square-on in both paper hands',
101: 'an elderly woman cut from photographic paper with one paper palm flat on the surface, a paper calendar strip of four squares floating above her shoulder',
104: 'VIZ: two paper piles of coins standing apart with a wide stretch of bare newsprint between them and a small elderly cut-out figure standing alone in that gap',
105: 'DESK: an elderly man cut from photographic paper at a paper desk with an open blank notebook and a teacup, a numeral 5 cut from mustard card pinned behind him',
108: 'an elderly woman cut from photographic paper dipping her head strip once, five small blank paper cards fanned out beside her',
112: 'an elderly couple cut from photographic paper seated side by side turning their head strips toward the camera, a cut-out paper bell shape behind them',
113: 'DESK: an elderly man cut from photographic paper at a paper desk with a closed blank notebook and a teacup, torn calendar sheets fanned at the edge',
114: 'CROWD: a small coffee shop in flat paper panels seen from inside, an elderly master cut-out behind the counter and two customer cut-outs at the paper tables, a numeral 68 cut from card on the wall',
115: 'VIZ: five paper envelopes standing in a row on a paper shelf, three still sealed and dulled with grey halftone dust, an elderly man cut from photographic paper reaching for one',
116: 'DESK: an elderly man cut from photographic paper at a paper desk with a calculator cut from grey card and a fan of receipts, a numeral 1 cut from mustard card pinned behind',
117: 'an elderly couple cut from photographic paper seated side by side bowing their head strips, paper accent shapes drifting behind them',
}

# scene_index -> chuyển động viết tay (đi vào `beats23.MOTION`)
MOTION_V3 = {
2:   'the huge 1,560,000 slams down from the top edge and the four calendar sheets fan out hard beneath it',
3:   'the coin strip whips across the frame and the scissors snap shut, sending the last two coins spinning off',
4:   'his brow strip jerks together and the empty speech bubble pops open beside his head',
9:   'the postcard drops into the slot and the paper gate slams down, the flowing coins piling up hard behind it',
13:  'the form flips over on its hinge and slaps face-on to camera, the five ink bars snapping in one after another',
14:  'the drawer shoots open and the record cards fan out and spill toward her',
16:  'the severed paper bridge swings apart and the red 0 drops into the gap between the halves',
17:  'her raised hand swings forward and the row of envelopes fans out hard behind her shoulder',
18:  'envelopes rain down onto the doorsteps one after another, skipping four houses that stay bare',
19:  'the calculator skids across the desk and the three empty bars snap into outline behind her',
21:  'the two law volumes swing open together and the numerals 102 and 92 slap down onto their pages',
22:  'both hourglasses flip over at once and the sand starts running hard',
23:  'the leftmost block drops away through the surface and the remaining eleven snap tight to close the gap',
24:  'the forty-eight coins slide into their four rows one row at a time and the numeral 48 slams down beside them',
26:  'the big coin swings up into the foreground and the grid of small coins rushes away behind it',
27:  'the conveyor whips forward and the leading coin tips over the edge and drops out of frame',
28:  'the thought bubble pops open above his head and the calculator skids toward the camera',
30:  'the envelope splits into four torn paths that shoot down the frame one after another',
31:  'the thick envelope drops out of frame and the thin postcard swings up into its place',
33:  'the postcard flies forward until it fills the frame while the thick envelope shrinks away behind',
35:  'a fresh paper square drops into the gap in the bar and the whole bar jolts level',
36:  'his chin snaps up and the last bar shoots up to close the gap to the dashed line',
37:  'she thrusts the sheet forward until it fills the frame and the taped arrow whips out from her hand',
39:  'the scissors snap shut on the long bar and the severed piece flies off to the side',
41:  'two postcards drop onto the timeline notches one after another with a hard slap',
42:  'the postcard slides off the table edge and drops out of frame as her chin falls',
43:  'the balance swings hard and settles with the thin postcard pan slamming down low',
44:  'the second letterhead shoots forward past the first and the taped arrow snaps out of frame',
45:  'trays of envelopes slide along the counter and one envelope sails right out of frame',
46:  'the envelope smacks into the door, bounces back and tumbles away across the frame',
47:  'the stack of forms slides across the counter and the clerk cut-out swings round to face it',
48:  'the envelope races along the taped arrow from one house to the next and stops dead at the numeral 1',
50:  'the envelope rockets out over the paper sea along the dotted tape line toward the far coast',
51:  'the four envelopes drop into their row one after another and the big 4 slams down above them',
52:  'the documents scatter across the desk and the numeral 3 drops into place on the wall behind',
53:  'the first envelope is swallowed by the slot, tape slaps across it, and the second envelope smacks into the seal',
55:  'his palms swing up fast and three blank paths fan out hard behind his shoulders',
57:  'the blank document shoots out of the screen and lands flat, the numeral 101 slapping onto it',
58:  'he swings the handset up to his ear and the cord whips across the frame to the envelope',
59:  'the queue surges forward a step together and the clerk cut-out swings round at the window',
61:  'both figures dip their heads together and paper accent shapes burst outward behind them',
62:  'the notebook flips open and a torn calendar sheet sails across the desk',
63:  'she settles into place as the numerals 66 and 61 drop onto the wall behind her one after the other',
64:  'the four calendar sheets tear off and fly away one after another, uncovering the face-down envelope',
66:  'her eyelids drop and the unopened envelope slides a little further toward the table edge',
67:  'the clock hand sweeps round hard and the small figure beneath is left standing still',
68:  'the lower calendar strip whips across and its last two squares tear away and fly off',
69:  'the top third of the note stack tears free and drops away out of her reach',
70:  'his head snaps round and the question-mark accent flips up behind his shoulder',
71:  'the right-hand slip is slapped across with dark tape and jolts back under the blow',
74:  'the stair of blocks shoots up step by step and the numeral 65 slams onto the first step',
76:  'her eyes snap wide and the two bar charts behind her shoot up, one climbing and one staying dead flat',
78:  'he thrusts the statement sheet forward and the taped arrow whips out toward the counter',
79:  'the wrong ledger line is yanked out and a brighter strip slaps into the empty slot',
80:  'forms slide across all three desks at once and the clerk cut-outs swing round together',
81:  'the postcard swings up beside her face and the numeral 1 drops in hard beside it',
82:  'the postcard drops onto the first square of the grid and the whole grid jolts',
84:  'his hands fly up to the sides of his head as the gate behind him slams the rest of the way down',
86:  'the gate crashes down and the coins pile up hard against it, the far channel emptying out',
87:  'the passbook swings open toward the camera and the taped arrow snaps into the torn gap',
89:  'she lifts one slip clear of the pile and the taped circle slaps onto it',
90:  'the postcard flips flat toward the camera and a torn paper tick drops into the empty box',
91:  'documents scatter across the desk and the checklist behind him snaps into place',
93:  'her head tilts sharply and the two calendar squares swing in beside her head',
94:  'the red ring slams onto the earlier square and his pointing arm swings toward it',
98:  'the yellowed certificate is swept aside out of frame and the fresh one slaps down in its place',
99:  'the small envelope races along the calendar strip and stops well short of the marked square',
100: 'he thrusts the certificate forward until it fills the frame',
101: 'her palm smacks down on the surface and the four calendar squares swing in above her shoulder',
104: 'the two coin piles slide apart hard, opening the bare gap wider around the small figure',
105: 'the notebook flips open and the numeral 5 drops onto the wall behind him',
108: 'her head snaps down once and five blank cards fan out beside her',
112: 'both figures swing round to camera and the paper bell shape drops in behind them',
113: 'he leans in hard and the torn calendar sheets fan out at the edge of the desk',
114: 'the master cut-out swings round behind the counter and the numeral 68 drops onto the wall',
115: 'his hand shoots out toward the shelf and the five envelopes rock back in their row',
116: 'the receipts fan out across the desk and the numeral 1 slams onto the wall behind',
117: 'both figures hinge forward into a deep bow and paper accents drift down behind them',
}
