# -*- coding: utf-8 -*-
r"""telop27.py — chữ hiện trên khung cho 86 ô của video 27.

LUẬT VIẾT TELOP (đừng sửa nếu chưa đọc):
  · Chữ rút TỪ CHÍNH lời đọc của ô đó. ⛔ Không thêm số mới, không thêm chế độ mới —
    YMYL: mọi số phải đã có trong `_TTS.md` và FACT SHEET (`nenkin/CLAUDE.md` §③).
  · Dòng chính ≤ 9 ký full-width/dòng, tối đa 2 dòng → đọc được ở điện thoại.
  · `circle=True` chỉ cho dòng CÓ SỐ và chỉ ở khoảnh khắc lật; `circle_line=i` khoanh đúng
    dòng thứ i (bản demo khoanh cả 2 dòng ⇒ rối).
  · màu: NAVY mặc định · RED cho mất mát/cảnh báo · TEAL cho phần được/giải pháp.
  · `sub` = thẻ trắng viền navy, ≤4 thẻ, mỗi thẻ ≤ 11 ký.
  · `stk` = sticker cast, 1 lần/ô, vào sau hero ~2,5s (`audience-45plus.md` §2.0f-bis).
"""
NAVY, RED, TEAL = (31, 56, 100), (192, 57, 43), (62, 124, 120)

TELOP = {
  0:  dict(big=["去年、いくら", "引かれましたか"], color=NAVY),
  1:  dict(big=["引かれるもの", "４つ"], color=NAVY,
           sub=["介護保険料", "後期高齢者医療", "所得税", "住民税"]),
  2:  dict(big=["42万3,700円"], color=RED, size=120, circle=True,
           sub=["どこにも", "載っていません"], stk="josei_surprised"),
  3:  dict(big=["欄は８つ", "該当は０行"], color=NAVY),
  4:  dict(big=["５つのうち", "３つ"], color=TEAL, circle_line=1,
           sub=["おひとり暮らしの方"]),
  5:  dict(big=["請求しないと", "動きません"], color=RED),
  6:  dict(big=["人生の順に", "５つ"], color=NAVY),
  7:  dict(big=["あなたの数字を", "計算します"], color=TEAL),
  8:  dict(big=["まず、事実から"], color=NAVY),
  9:  dict(big=["①特別支給の", "老齢厚生年金"], color=NAVY),
  10: dict(big=["昭和41年4月1日", "以前生まれ"], color=NAVY, sub=["女性", "男性は36年"]),
  11: dict(big=["自動的には", "始まりません"], color=RED),
  12: dict(big=["厚生労働省の", "資料より"], color=NAVY),
  13: dict(big=["時効は５年"], color=RED, size=120, circle=True),
  14: dict(big=["遅いほど", "減っていく"], color=RED),
  15: dict(big=["仙台の佐藤さん", "66歳"], color=NAVY),
  16: dict(big=["受給権は", "61歳のとき"], color=NAVY),
  17: dict(big=["紙は引き出しに", "積まれたまま"], color=NAVY),
  18: dict(big=["気づいたのは", "４年10か月後"], color=RED),
  19: dict(big=["時効まで", "あと２か月"], color=RED, circle_line=1, stk="josei_surprised"),
  20: dict(big=["156万円"], color=TEAL, size=132, circle=True, sub=["一括で受取"]),
  21: dict(big=["あの紙には", "一行もない"], color=NAVY),
  22: dict(big=["①出さないと", "入らない"], color=RED),
  23: dict(big=["②加給年金"], color=NAVY, sub=["厚生年金20年以上", "配偶者65歳未満"]),
  24: dict(big=["42万3,700円"], color=RED, size=120, circle=True,
           sub=["配偶者分24万3,800", "特別加算17万9,900"]),
  25: dict(big=["月に約", "３万５千円"], color=TEAL),
  26: dict(big=["大阪の", "山田さんご夫妻"], color=NAVY, sub=["夫67歳", "妻65歳"]),
  27: dict(big=["様式第", "二百二十九号"], color=NAVY),
  28: dict(big=["戸籍抄本を", "添えて提出"], color=NAVY),
  29: dict(big=["もう知って", "いるはずでは？"], color=NAVY),
  30: dict(big=["記録がある", "≠ 支給が始まる"], color=RED),
  31: dict(big=["②出さないと", "入らない"], color=RED),
  32: dict(big=["③配偶者が", "65歳になる月"], color=NAVY),
  33: dict(big=["奥さまの誕生日", "赤飯を炊いた月"], color=TEAL),
  34: dict(big=["３万５千円", "減っている"], color=RED, circle_line=0, stk="josei_surprised"),
  35: dict(big=["加給年金は", "打ち切られます"], color=RED),
  36: dict(big=["日本年金機構", "の文章より"], color=NAVY),
  37: dict(big=["代わりに", "上乗せがつく"], color=TEAL),
  38: dict(big=["振替加算"], color=TEAL, size=120, sub=["昭和36年8月生", "厚生年金12年"]),
  39: dict(big=["1万6,335円"], color=TEAL, size=120, circle=True),
  40: dict(big=["差は約", "40万円"], color=RED, circle_line=1),
  41: dict(big=["東京の高橋さん", "奥さまは41年6月生"], color=NAVY),
  42: dict(big=["２か月、", "外れています"], color=RED),
  43: dict(big=["1万6千円", "と ０円"], color=RED, circle_line=1),
  44: dict(big=["制度の線が", "引かれている"], color=NAVY),
  45: dict(big=["高評価と", "シェアを"], color=TEAL),
  46: dict(big=["同じ出来事、", "違う結果"], color=NAVY),
  47: dict(big=["この振替加算", "届は要る？"], color=NAVY),
  48: dict(big=["原則、", "要りません"], color=TEAL, size=120, stk="josei_relieved"),
  49: dict(big=["ただし", "順番次第"], color=RED, sub=["妻65歳のあとに", "夫が20年到達"]),
  50: dict(big=["③印は", "三角"], color=NAVY),
  51: dict(big=["④年金生活者", "支援給付金"], color=NAVY),
  52: dict(big=["月5,620円"], color=TEAL, size=120, circle=True, sub=["年6万7,440円"]),
  53: dict(big=["納めた期間で", "変わります"], color=NAVY),
  54: dict(big=["福岡の伊藤さん", "68歳"], color=NAVY, sub=["国民年金のみ", "月6万5千円"]),
  55: dict(big=["所得が基準を", "少し超えた"], color=RED),
  56: dict(big=["その年から", "止まりました"], color=RED),
  57: dict(big=["次の年、", "所得は戻った"], color=NAVY),
  58: dict(big=["給付金は", "戻らなかった"], color=RED, stk="josei_worried"),
  59: dict(big=["自動では", "復活しません"], color=RED),
  60: dict(big=["毎年９月", "はがきが届く"], color=NAVY),
  61: dict(big=["④出さないと", "入らない"], color=RED),
  62: dict(big=["⑤未支給年金"], color=NAVY),
  63: dict(big=["年金は", "２か月分の後払い"], color=NAVY),
  64: dict(big=["上越市の", "中村さん71歳"], color=NAVY, sub=["調理員40年", "夫は10年前に"]),
  65: dict(big=["２か月分", "約25万円"], color=TEAL, size=120, circle_line=1),
  66: dict(big=["相続財産では", "ありません"], color=NAVY),
  67: dict(big=["死亡届は", "省略できる"], color=TEAL),
  68: dict(big=["請求は", "省略できない"], color=RED, stk="josei_surprised"),
  69: dict(big=["止めるのは自動", "受け取るのは手動"], color=RED),
  70: dict(big=["何を出したか", "覚えていない"], color=NAVY),
  71: dict(big=["⑤出さないと", "渡らない"], color=RED),
  72: dict(big=["答えは", "③振替加算"], color=TEAL, size=120),
  73: dict(big=["ただし", "例外が一つ"], color=RED),
  74: dict(big=["原則は自動", "例外は手動"], color=NAVY),
  75: dict(big=["研究ノート"], color=NAVY, size=120,
           sub=["①８欄・０行", "②時効５年"]),
  76: dict(big=["②自動では", "始まらない"], color=NAVY),
  77: dict(big=["③様式229号"], color=NAVY, size=112),
  78: dict(big=["④配偶者65歳で", "打ち切り"], color=NAVY),
  79: dict(big=["⑤請求は", "省略できない"], color=NAVY),
  80: dict(big=["今日からの三つ"], color=TEAL, size=112, sub=["①通知書を出す"]),
  81: dict(big=["②配偶者の", "生年月日"], color=TEAL, sub=["昭和41年4月1日"]),
  82: dict(big=["③年金事務所へ", "電話を一本"], color=TEAL),
  83: dict(big=["2026年9月", "時点の情報です"], color=NAVY),
  84: dict(big=["支給日の前に", "直前チェック"], color=TEAL),
  85: dict(big=["また次回の", "研究で"], color=NAVY),
}
