# -*- coding: utf-8 -*-
"""Tu khoa Pexels cho tung shot anh (key = shot id). "AI" = stock khong co / canh an du -> giu prompt AI.
("v", q) = uu tien VIDEO (canh co chuyen dong nhe: rot tra, rem bay, song...)."""
Q = {
0: "woman cleaning out closet boxes", 1: "cluttered closet boxes", 2: "garbage bags pile room",
3: "paper shopping bag close up", 4: "garbage bag trash", 5: "elderly asian woman sitting alone night",
6: "sliding door japanese room", 7: ("v", "tea cup steam night lamp"), 8: "hands folding paper bag",
9: "AI", 10: "empty closet sunlight", 11: "old wooden drawer", 12: "envelope in paper bag",
13: "envelope on ground", 14: ("v", "pouring green tea teapot"), 16: "stack of paper bags",
17: "paper bags wrapping paper", 18: "woman holding paper bag trash", 19: "putting box on shelf",
20: "elderly woman counting papers", 21: "elderly asian woman laughing", 22: "elderly asian woman smiling",
23: "AI", 24: "AI", 25: "old hands paper", 26: "cluttered storage room", 27: "cluttered shelf boxes",
28: "elderly woman searching boxes", 29: "AI", 30: "japanese room plant window", 31: ("v", "opening window curtain breeze"),
32: "empty cardboard box floor", 33: "cardboard box organized", 34: "paper recycling bundle", 35: "elderly woman reading window",
36: "empty shelf sunlight", 38: "kitchen cupboard boxes", 39: "japanese teacups set", 40: "teacup in box",
41: "chipped cup", 42: "hands holding teacup", 43: "closing box lid", 44: "AI", 45: "dusty shelf cup",
46: "cracked cup", 47: "cracked ceramic cup close up", 48: "old hands holding cup", 49: "cup table window rain",
50: "unboxing teacup", 51: ("v", "pouring tea into cup"), 52: ("v", "hands holding tea cup steam"),
53: "elderly asian woman drinking tea window", 54: "breakfast tray tea", 55: "breakfast table flower vase",
57: "stack of postcards", 58: "formal dinner banquet people", 59: "elderly woman walking alone evening",
60: "woman phone hesitating", 61: "elderly woman bench park autumn", 62: "pen paper hesitation",
63: "old japanese book brush", 65: "calligraphy brush inkstone", 66: ("v", "moon reflection pond"),
67: "pencil circle paper", 68: "postcards ribbon", 69: "elderly woman writing letter", 70: "elderly woman holding card smiling",
71: "senior women cafe laughing", 72: "two elderly women walking park", 74: "ironing board towels",
75: "woman scrubbing floor", 76: "AI", 77: "thread rope tension", 78: "woman tired shoulder",
79: "messy closet overwhelmed", 80: "AI", 81: "office evening clock", 82: "woman smelling towel sunlight",
83: ("v", "laundry drying balcony sun"), 84: "elderly woman stretching balcony", 85: "tidy drawer",
86: "folded towels basket", 87: "woman tea afternoon sun", 88: "cozy living room",
90: "elderly woman telephone", 91: "old family photo frame", 92: "elderly woman sitting phone",
93: "AI", 94: "empty childrens room desk", 95: "telephone night", 96: "woman phone sofa tired",
97: "woman on phone smiling", 98: "heavy bundle cloth", 99: "clock evening phone",
100: "coffee grinder beans", 101: ("v", "hand coffee grinder"), 102: "telephone ringing", 103: "elderly woman phone smiling coffee",
104: "woman phone kitchen smiling", 105: "two hands holding", 107: "telephone flower table",
109: "woman showing phone photos cafe", 110: "women talking cafe", 111: "woman listening cafe smile",
112: "elderly woman walking street dusk", 113: ("v", "person standing crowd walking past"), 114: "elderly woman tea home",
115: "AI", 116: "flower pots row", 117: "beautiful garden fence", 118: "garden weeds gloves",
119: "woman alone large house window", 120: "woman reflection window", 121: "empty shelf light",
122: "teacup morning light", 123: "elderly woman walking sunset", 125: "coats hanging wardrobe",
126: "child crayon drawing", 127: "opening old drawer", 128: "woman hugging sweater",
129: "quiet room soft light", 130: "moving boxes truck", 131: "throwing letters box", 132: "empty clean room",
133: "choosing sweater clothes", 134: "woman holding sweater smiling", 135: "AI", 137: ("v", "mountain river stream"),
138: "old japanese town river", 139: "framed drawing shelf flowers", 140: "elderly woman cardigan window",
141: "framed child drawing wall", 142: "cozy living room chair cardigan", 143: "wooden box shelf",
144: "lamp teacup evening", 145: "elderly woman room boxes", 146: "elderly woman closet grandson",
147: "fountain pen paper bag", 148: "envelope fountain pen", 149: "japanese buddhist altar home",
150: "opening envelope scissors", 153: "elderly woman laughing letter", 155: "old book lamp desk",
157: "minimalist japanese room", 158: "elderly woman sitting calm tatami", 159: "book letter table",
160: "putting letter paper bag", 161: "elderly woman window spring", 162: "elderly woman smiling gently",
163: "closing closet door", 164: ("v", "window curtain wind bright room"), 165: "elderly women greeting door",
166: "empty shelf plant", 167: ("v", "morning light empty room"), 168: "elderly woman thinking tea",
169: "kimono drawing letter sweater", 170: "teacup notebook night window", 171: "elderly women bench talking",
172: ("v", "night street warm windows"), 173: "cozy room radio tea night", 174: ("v", "moon night window"),
}
