# -*- coding: utf-8 -*-
"""Mo ta hinh cho 162 shot anh — yawa bai 1 (v7). id = shots.json['id'].
Token nhan vat: {K}=Kazuko (nguoi quen) · {Y}=nguoi nghe (luon quay lung/chi thay tay) ·
{D}=con gai 45 · {F}=ban cu sanh dieu · {H}=chong (chi thay lung / trong ky uc)."""

CAST = {
    "K": "Kazuko, a Japanese woman of about 70 with short soft grey hair in a neat bob, a gentle round face and a soft coral-pink cardigan over a white blouse",
    "Y": "an older Japanese woman seen only from behind or from the shoulders down, her face never shown, shoulder-length grey hair and a lavender cardigan",
    "D": "a Japanese woman in her mid forties with dark hair tied back and a navy blouse",
    "F": "a stylish Japanese woman in her late sixties with a beige coat and pearl earrings",
    "H": "an elderly Japanese man in a brown knitted cardigan, seen only from behind",
}

S = {
0: "{D} kneeling alone in front of a wide-open oshiire closet crammed with paper shopping bags and boxes, looking tired and bewildered, evening light",
1: "the same open oshiire closet seen from the doorway, {D} small in the frame, stacks of paper bags spilling out, quiet empty apartment",
2: "{D} tying a full white garbage bag, many more garbage bags lined up on the tatami behind her, a small pile of old boxes",
3: "close-up of a paper bag on the tatami, a small wooden keepsake box half hidden among crumpled wrapping paper inside it",
4: "a garbage bag with a small precious wooden box sinking among ordinary junk, soft sad lighting",
5: "{Y} sitting on a zabuton cushion at night facing a closed oshiire door, one hand resting over her chest",
6: "{Y}'s hand gently sliding the oshiire paper door closed, warm lamp light from the side",
7: "a warm room at night, a soft lamp and a steaming teacup on a low table, gentle and forgiving mood",
8: "{Y}'s hands carefully folding a paper shopping bag into a neat square, tender and careful",
9: "seven small softly glowing knots of string resting on a wooden table, symbolic and calm",
10: "an oshiire closet with its doors open and a few neat things inside, sunlight and a light breeze coming in",
11: "a single old wooden tansu drawer slightly open, a soft glow coming from inside it, mysterious and quiet",
12: "the bottom of a paper shopping bag with a plain sealed envelope lying in it, soft light falling on it",
13: "a plain envelope lying on the ground next to a garbage bag at a collection point, early morning, lonely mood",
14: "a teapot pouring green tea into a teacup on a low table, cosy night, warm lamp light",
16: "the upper shelf of an oshiire closet completely packed with folded paper shopping bags tied with rubber bands",
17: "a flat-lay of department-store paper bags, an empty sweets tin and neatly folded wrapping paper on tatami",
18: "{Y} holding a paper bag above a garbage bag, frozen and hesitating",
19: "{Y} putting the paper bag back onto the shelf with a small sigh",
20: "{K} sitting on tatami counting folded paper bags one by one, a big pile beside her",
21: "{K} laughing with a hand over her mouth, surrounded by a mountain of paper bags",
22: "{K} smiling warmly at the viewer's side, holding one paper bag, afternoon light",
23: "a sepia-toned memory of a Showa-era kitchen, a mother smoothing out used wrapping paper at a small table",
24: "a sepia memory of a mother winding used string into a ball, a child watching beside her",
25: "old hands carefully flattening a piece of wrapping paper on a table, respectful warm light",
26: "a calendar-free wall and a full closet, dust in the air, a sense of 'someday' that never comes, soft grey tones",
27: "an overstuffed oshiire where small precious objects are hidden behind boxes, only a corner of a wooden box visible",
28: "{K} on her knees surrounded by opened bags, searching, a wall clock above her",
29: "a Japanese room with air flowing gently around the furniture, soft translucent light ribbons suggesting 'ki' energy",
30: "a folding screen and a potted plant by a window, calm neutral mood",
31: "{Y} sliding open a window, curtains lifting in the breeze, bright fresh daylight",
32: "an empty cardboard box set on the tatami in front of the oshiire, simple and hopeful",
33: "a cardboard box neatly filled with a few paper bags, the rest tied in bundles for recycling",
34: "bundles of paper bags tied with string by the front door, ready to go out, morning light",
35: "{Y} sitting at a sunny window with free time, a book and a teacup, relaxed",
36: "a half-empty oshiire shelf with a clear space, sunlight on the wooden floor of the closet",
38: "the back of a kitchen cupboard with unopened boxed tableware stacked inside",
39: "a boxed set of flower-patterned teacups and elegant tea cups still in their tissue paper",
40: "a pretty teacup sitting unused in its box inside a dark cupboard",
41: "{Y}'s hand holding a chipped cheap teacup at the breakfast table, morning light",
42: "{Y}'s hands hesitating over a delicate teacup, afraid to take it out",
43: "a delicate teacup being put back into its box, the lid closing",
44: "a sepia memory of a mother mending a teacup carefully, respectful of things",
45: "a beautiful teacup gathering dust on a high cupboard shelf, a little lonely",
46: "a chipped teacup with a crack on a plain table, soft muted colours",
47: "a crack in a teacup catching the light, subtle and quiet",
48: "a close-up of old hands wrapped around a chipped teacup",
49: "a small table with a chipped cup, a faintly wistful mood, overcast window light",
50: "{Y} taking the flower-patterned teacup out of its box, gentle anticipation",
51: "a small clay teapot pouring tea into the flower-patterned teacup, steam rising",
52: "two hands cupping the warm flower-patterned teacup, steam curling up",
53: "{Y} sipping tea from the beautiful teacup by a sunny window, contented",
54: "the flower-patterned teacup on a small tray set for one, a neat breakfast table",
55: "a morning table with the good teacup and a small flower in a vase, bright and cheerful",
57: "{Y}'s hands flipping through a thick stack of blank New Year postcards on a low table",
58: "a group of people at a formal banquet table, polite stiff smiles, seen from a distance",
59: "{Y} walking home alone at dusk after a dinner, shoulders slightly heavy",
60: "{Y} holding a phone and a blank postcard, hesitating at the table",
61: "{Y} sitting alone on a bench in a small park, autumn leaves, lonely feeling",
62: "a hand hovering over a pen and blank postcards, unable to write",
63: "an old hand-bound Japanese book lying open on a wooden desk with a brush and inkstone, candle light, classical mood",
65: "a lone ink brush resting beside an inkstone, calm and still",
66: "a still pond reflecting the moon, clear and quiet mind",
67: "{Y}'s hand drawing small red circles next to some blank postcards with a pencil",
68: "a neat small stack of chosen postcards tied with a ribbon",
69: "{K} writing carefully on a postcard at her low table with a gentle smile",
70: "{K} holding up a finished postcard with quiet satisfaction",
71: "{Y} meeting an old friend at a small cafe, both laughing warmly",
72: "two older women walking side by side under spring trees, close and relaxed",
74: "an ironing board with neatly pressed towels and handkerchiefs stacked high",
75: "{Y} scrubbing a wooden floor on her knees in an empty tidy room",
76: "a sepia memory of a busy Showa-era office with rows of desks and paperwork",
77: "a tightly stretched thread about to snap, symbolic, soft background",
78: "{Y} rubbing her shoulder at the end of the day, tired",
79: "{Y} standing in front of a messy closet, overwhelmed, not knowing where to start",
80: "a sepia memory of a bank counter in the Showa era, {K} younger, counting banknotes with fast fingers",
81: "a bank office at closing time, a clock on the wall, staff still working under fluorescent light",
82: "{K} on a sunny balcony burying her face in a sun-dried towel, eyes closed",
83: "{K} smiling with the towel in her arms, laundry fluttering, bright blue sky",
84: "{K} rolling her shoulders, relaxed and free on the balcony",
85: "a single kitchen drawer neatly tidied, everything else left as is",
86: "a folded ironing board leaning against the wall, towels stacked unironed but soft",
87: "{Y} having a cup of tea in the late afternoon sun, a moment of rest",
88: "a cosy lived-in living room, not perfect, warm and welcoming",
90: "{Y} holding a telephone receiver, a worried look in her posture",
91: "a family photo frame on a shelf showing a young mother with a small child, soft light",
92: "{Y} sitting by the phone with her hands in her lap, torn",
93: "a sepia memory of a young mother carrying a child on her back while cooking",
94: "{Y} standing in an empty children's room with a small old desk, quiet",
95: "{Y}'s hand resting on a telephone at night",
96: "{D} on a sofa in her own apartment holding a phone to her ear, eyes rolling a little, tired after work",
97: "{D} smiling a little helplessly on the phone",
98: "a big heavy bundle wrapped in a furoshiki cloth, symbolic of burden",
99: "{K} sitting by her phone at seven o'clock not picking it up, a clock showing evening",
100: "{K} scooping coffee beans into a small hand grinder at her kitchen table",
101: "a close-up of a hand-crank coffee mill being turned, beans and warm lamp light",
102: "a telephone on a small table ringing, {K} turning towards it in surprise",
103: "{K} on the phone smiling warmly, a coffee cup in her other hand",
104: "{D} on the phone in her kitchen, smiling softly",
105: "two hands, one older and one younger, loosely holding a soft thread between them",
106: "{D} reaching out a hand towards the viewer warmly",
107: "a telephone resting quietly, a teacup and a flower beside it",
109: "{F} at a cafe table showing travel photos on her phone, excited",
110: "{F} talking animatedly about her new house, gesturing",
111: "{Y} nodding with a polite smile across the cafe table",
112: "{Y} walking home alone along a quiet street at dusk, looking down",
113: "{Y} standing still while other people walk past quickly, feeling left behind",
114: "a gentle warm scene of {Y} at home with a cup of tea, reassuring",
115: "a sepia collage of school report cards, a job interview and a wedding, soft vintage feel, all papers blank",
116: "rows of identical flower pots on a shelf, one small pot slightly apart",
117: "a beautiful garden seen over a wooden fence, bright flowers",
118: "the same garden from the inside with weeds and a gardening glove, honest and ordinary",
119: "{F} sitting alone in a large quiet house, looking out of the window",
120: "{Y} looking at her own reflection in a window, calm and gentle",
121: "a slightly emptier oshiire shelf with sunlight on it",
122: "the flower-patterned teacup on a table in morning light",
123: "{Y} walking home in warm evening light, shoulders relaxed, a small smile in her posture",
125: "a man's coat and sweaters hanging in an old wardrobe",
126: "a child's crayon drawing of a family kept in a drawer, the drawing has no words",
127: "{Y} opening an old wooden tansu drawer, a faint wisp suggesting the smell of camphor",
128: "{Y} holding a man's brown cardigan to her chest, head bowed",
129: "a quiet room with soft light, gentle understanding mood",
130: "a moving truck and cardboard boxes outside a house, a rushed day",
131: "an older woman seen from behind throwing a bundle of letters into a box of trash",
132: "an empty tidy room with bare walls, cold and a little too clean",
133: "two hands choosing one sweater from a pile of clothes",
134: "{Y} holding one chosen item gently, a soft smile",
135: "an old hut in the mountains by a stream, classical Japanese ink-wash feel",
137: "a clear mountain river flowing over stones, sparkling light",
138: "an old Japanese town along a river, people and houses changing with the seasons",
139: "a small framed child's drawing displayed on a shelf with a vase of flowers",
140: "{Y} wearing a man's brown cardigan with the sleeves rolled up, standing by the window",
141: "a framed crayon drawing hanging on a sunny living-room wall",
142: "a warm living room with a keepsake cardigan on a chair and a framed drawing, lived-in and happy",
143: "a single wooden box on a shelf, chosen with care, soft light",
144: "an evening room with a lamp and a teacup, storytelling mood",
145: "{K} sitting among neat stacks of paper bags, peaceful",
146: "{K} in winter at home, searching the oshiire, a teenage grandson in school uniform waiting behind her",
147: "{K} pulling a fountain pen out of a paper bag inside another paper bag, astonished",
148: "a plain sealed envelope lying under the fountain pen in the bottom of a paper bag",
149: "{K} sitting before a small Buddhist altar with the envelope placed in front of it, hands folded",
150: "{K}'s hands carefully cutting open the envelope with small scissors, one sheet of letter paper inside",
153: "{K} laughing out loud with tears in her eyes, holding the letter",
155: "an old hand-bound book open on a desk beside the letter, evening lamp",
157: "a simple uncluttered Japanese room, sunlight and a single vase, calm",
158: "{K} sitting upright and serene in her tidy room",
159: "the old book and the letter side by side on a low table, soft light",
160: "{K} placing the letter into a single paper bag on the oshiire shelf",
161: "{K} looking out of the window at a clear spring sky",
162: "{K} smiling gently with her hand on the paper bag",
163: "{K} sliding the oshiire door closed, calm and light",
164: "a bright tidy room with the window open, fresh air",
165: "{Y} welcoming a friend at her front door, both smiling",
166: "an empty shelf with a single small plant, peaceful space",
167: "morning light falling into an empty corner of a room, full of possibility",
168: "{Y} sitting at a low table thinking, a teacup in her hands",
169: "a kimono, a child's drawing, an old letter and a man's sweater laid out gently on tatami",
170: "a teacup and a notebook on a table by a night window",
171: "two older women talking warmly on a park bench",
172: "a quiet night street with warm lit windows",
173: "a cosy room with a radio and tea at night",
174: "a night window with the moon, a teacup and a small lamp, peaceful ending",
}
